### DISCUSSION TITLE
Feature request - Foldable items

### DISCUSSION THREAD

**Discussion by Jonny-T-cyber** [elchininet/custom-sidebar#190] [Q&A]
Good morning,
Is there the possibility of implementing an expandable folding function for the items?
For example I have the item "Test" and, by clicking on this, several items expand (Test 1, Test 2. Test 3, etc. ):

- Test
-- Test 1
-- Test 2
-- Test 3

I think it would be very useful, for me but also for many other users who would like to have this functionality.

Thank you

**Comment by elchininet** [comment]
Hi @Jonny-T-cyber,
Please, consult [this discussion](https://github.com/elchininet/custom-sidebar/discussions/113) and my answer there. That would not be an easy task to do and it would require a lot of work and maintenance, but if you think that there are many users that would like to have that functionality try to revive [this feature request](https://community.home-assistant.io/t/dropdown-and-collapsible-submenus-in-the-left-menu-panel/549738). If it gets traction among the community members and it is not implemented in Home Assistant I would consider to implement it in this custom plugin.
Regards

**Comment by Mariusthvdb** [comment]
Not trying to take away from your FR, but, isnt this

> * Test
>   -- Test 1
>   -- Test 2
>   -- Test 3

exactly what the dashboards and its underlying views do. Have a main Test dashboard, and show the test1/test2/test3 views inside that.

As a matter of fact, it has been what I have for years.... literally:

<img width="627" alt="Scherm­afbeelding 2024-11-13 om 17 00 29" src="https://github.com/user-attachments/assets/090f1db4-9245-4332-b93b-a45604e4b063">


<img width="1445" alt="Scherm­afbeelding 2024-11-13 om 16 54 31" src="https://github.com/user-attachments/assets/38c06de9-bee7-48b8-a4d7-3225df3ac443">

**Reply by NODeeJay** [reply]
> Not trying to take away from your FR, but, isnt this
> 
> > * Test
> >   -- Test 1
> >   -- Test 2
> >   -- Test 3
> 
> exactly what the dashboards and its underlying views do. Have a main Test dashboard, and show the test1/test2/test3 views inside that.
> 
> As a matter of fact, it has been what I have for years.... literally:

Actually not, well, not in that form. Yes, it provides a certain hierarchical level, but it's not the grouping of dashboards OP wants and me too.
Imagine:

Sensor Management
- ESPHome Builder
- Integrations
- Tasmota
- Zigbee2MQTT

or

System Management
- Log Viewer
- SSH
- Portainer

In my case, I would be very happy to get things ordered where most of the time I use a couple of items only and could hide the rest in an "expansion". I do not need and actually do not even want a dashboard opening when I press the expandable item but just showing the items in the expand. I could well imagine an implementation like this based on the examples above:

```
order:
  - expand: true
    order: 1
    name: Sensor Management
    icon: mdi:chip
    items:
      - item: ESPHome Builder
        order: 1
      - item: Integrations
        order: 2
      - item: Tasmota
        order: 3
      - item: Zigbee2MQTT
        order: 4
  - item: System Management
    order: 2
    expand: true
    icon: mdi:earth
    items:
      - item: Log Viewer
        order: 1
      - item: SSH
        order: 2
      - item: Portainer
        order: 3
```
I do not need it with multiple layers, but I could imagine use for it aka:
```
order:
  - expand: true
    order: 1
    name: Expand 1
    icon: mdi:chip
    items:
      - item: Item 1
        order: 1
      - expand: true
        order: 2
        name: Expand 2
        icon: mdi:chip
        items:
          - item: Item 1
            order: 1
          - item: Item 2
            order: 2
```

And this as addition would make it perfect:
```
order:
  - divider: true
    name: Tools
    icon: mdi:tools 
```
If **name** is omitted, the **icon** and **horizontal divider** are shown, if also **icon** is omitted just the **horizontal divider** is shown and if **name** but not **icon** is present, the **name** and **horizontal divider** is shown.
Feasible? Considerable?
