### DISCUSSION TITLE
Spacer in Sidebar

### DISCUSSION THREAD

**Discussion by quietatsunset** [elchininet/custom-sidebar#268] [Q&A]
Why is my configuration inserting this spacer in the sidebar?

![Screenshot 2024-12-28 141147](https://github.com/user-attachments/assets/48556aa4-4b68-4f73-87fc-4d3bd93110b7)

```
order:
  - item: overview
    order: 0
  - item: energy
    order: 1
  - item: logbook
    order: 2
  - item: history
    order: 3
  - item: terminal
    order: 4
  - item: studio code server
    order: 5
  - item: config
    bottom: true
    order: 6
  - item: hacs
    bottom: true
    order: 7
    notification: |
      [[[
        const outdatedHacsEntities = Object.values(entities.update).filter(
          (entity) => entity.platform === 'hacs' && is_state(entity.entity_id, 'on')
        );
        return outdatedHacsEntities.length || '';
      ]]]
  - new_item: true
    item: Logs
    bottom: true
    href: "/config/logs"
    icon: mdi:math-log
    order: 8
  - item: developer tools
    name: Dev tools
    icon: mdi:tools
    bottom: true
    order: 9
  - item: snapshots
    hide: true
  - item: backups
    hide: true
  - item: map
    hide: true
  - item: media
    hide: true
  - item: calendar
    hide: true
```
