### DISCUSSION TITLE
Config should apply to everybody, but everyone except me should have 'settings'. Is that possible?

### DISCUSSION THREAD

**Discussion by iAmRenzo** [elchininet/custom-sidebar#289] [Q&A]
I made a configuration for the sidebar which should apply for every user. But for everybody (2 users) except me there should be an exception for the 'settings' item. How can I accomplish that?

Would it be something like this? And how to I arrange the extend_from?
```
  - user:
    - Jim Hawkins
    - Long John Silver
    extend_from: user_config
  - item: settings
    hide: false
```

**Comment by elchininet** [comment]
Hi @iAmRenzo,
`item` is not a valid property of the main configuration, you need to add an `order` property and this property allows you to add items to it:

```yaml
exceptions:
  - user:
    - Jim Hawkins
    - Long John Silver
    extend_from: base
    title: My Home
    order:
      - item: settings
        hide: false
```
