### DISCUSSION TITLE
Why doesn't this configuration work?

### DISCUSSION THREAD

**Discussion by majorsl** [elchininet/custom-sidebar#301] [Q&A]
I wanted to add a new item to my order, but exclude a couple of users who would never use it, so I used exception:

When I reload HA, it obviously fails because the default sidebar is back with no customization.

```
title: My Home
sidebar_editable: false
order:
- item: overview
  name: Dashboard
  order: 0
- item: logbook
  order: 1
- item: developer-tools
  match: data-panel
  bottom: true
  order: 2
- item: settings
  bottom: true
- item: energy
  hide: true
- item: map
  hide: true
- item: map
  hide: true
- item: calendar
  hide: true
- item: media
  hide: true
- item: history
  hide: true
exceptions:
  - not_user:
    - 'Rachel'
    - 'Sam'
    order:
    - new_item: true
      item: Office Remote
      icon: mdi:remote
      href: "/lovelace/office-remote"
      order: 3
```
