### DISCUSSION TITLE
Multiple elements in single row

### DISCUSSION THREAD

**Discussion by eValker** [elchininet/custom-sidebar#410] [Show and tell]
Hi there,

I’d like to show you something I’ve been using for a while that’s useful for instances with lots of sidebar items. This “hack” lets you save a bit of space, making the sidebar (at least for me) more readable and easier to navigate—no scrolling required. It produces an effect like this:

(web browser)
![obraz](https://github.com/user-attachments/assets/41674900-62a3-4f9d-9f62-2a3e455fd8a4)
(mobile app)
![obraz](https://github.com/user-attachments/assets/f7de012f-0972-4c79-926d-a022b4bc8744)

Maybe this will be helpful to someone, or perhaps inspire someone to create something even more interesting :) In any case, the configuration code looks like this:

**(edit: fixed version in the comment below)**
```yaml
id: main_sidebar
partials:
  titleClick: |
    window.titleClick = () => {
      const path = '/lovelace';
      window.history.replaceState(null, '', path);
      window.dispatchEvent(
        new CustomEvent(
          'location-changed',
          {
            detail: {
              replace: path
            }
          }
        )
      );
    };
    
title: |
  [[[
    @partial titleClick
    return '<span onClick="javascript:titleClick()" onTouchEnd="javascript:titleClick()" style="cursor:pointer;">Home Assistant</span>';
  ]]]
order:
# top
    
# bottom
  - item: dashboard-admin
    href: "/dashboard-admin"
    match: href
    bottom: true
    order: 9
  - item: 45df7312_zigbee2mqtt
    href: "/45df7312_zigbee2mqtt"
    match: href
    bottom: true
    order: 10
    attributes:
      tp: zigbee2mqtt
  - item: a0d7b954_nodered
    href: "/a0d7b954_nodered"
    match: href
    bottom: true
    order: 11
    attributes:
      tp: nodered
  - item: hacs
    href: "/hacs"
    match: href
    bottom: true
    order: 12
    attributes:
      tp: hacs
  - new_item: true
    match: href
    item: Logs
    href: "/config/logs"
    icon: mdi:math-log
    order: 13
    attributes:
      tp: logs
    bottom: true
  - item: logbook
    match: href
    bottom: true
    order: 14
    attributes:
      tp: logbook
  - item: history
    match: href
    bottom: true
    order: 15
    attributes:
      tp: history
  - item: developer-tools
    icon: mdi:dev-to
    match: href
    bottom: true
    order: 16
    attributes:
      tp: dev-to
  - item: config
    icon: mdi:tune
    match: href
    bottom: true
    order: 17
    attributes:
      tp: config
    
#hidden
  - item: lovelace
    match: href
    hide: true 
  - item: map
    hide: true
    match: href
  - item: media
    hide: true
    match: href
  - item: energy
    match: href
    hide: true
  - item: calendar
    match: href
    hide: true
  - item: todo
    match: href
    hide: false
        
styles: |
  :host([expanded]) ha-md-list {
    display: grid;
    grid-template-columns: repeat(4, 25%);
    grid-template-rows: auto 1fr auto;
  }
  
  :host([expanded]) ha-md-list > ha-md-list-item {
    grid-column: 1 / 5;
    height: 48px;
  }
  
  :host([expanded]) ha-md-list > ha-md-list-item[tp] {
    width: 48px;
  }

  :host([expanded]) ha-md-list-item[tp="zigbee2mqtt"] > .item-text,
  :host([expanded]) ha-md-list-item[tp="nodered"] > .item-text,
  :host([expanded]) ha-md-list-item[tp="hacs"] > .item-text,
  :host([expanded]) ha-md-list-item[tp="logs"] > .item-text,
  :host([expanded]) ha-md-list-item[tp="logbook"] > .item-text,
  :host([expanded]) ha-md-list-item[tp="history"] > .item-text,
  :host([expanded]) ha-md-list-item[tp="dev-to"] > .item-text,
  :host([expanded]) ha-md-list-item[tp="config"] > .item-text
  {
    display: none !important;
  }

  :host([expanded]) ha-md-list-item[tp="zigbee2mqtt"] > .item-text,
  :host([expanded]) ha-md-list-item[tp="nodered"] > .item-text,
  :host([expanded]) ha-md-list-item[tp="hacs"] > .item-text,
  :host([expanded]) ha-md-list-item[tp="logs"] > .item-text,
  :host([expanded]) ha-md-list-item[tp="logbook"] > .item-text,
  :host([expanded]) ha-md-list-item[tp="history"] > .item-text,
  :host([expanded]) ha-md-list-item[tp="dev-to"] > .item-text,
  :host([expanded]) ha-md-list-item[tp="config"] > .item-text
  {
    width: 63px;
    padding-inline-start: 20px;
  }
 
  :host([expanded]) ha-md-list-item[tp="zigbee2mqtt"] {
    grid-column: 1 / 2;
  } 
 
  :host([expanded]) ha-md-list-item[tp="nodered"] {
    grid-column: 2 / 3;
  } 
 
  :host([expanded]) ha-md-list-item[tp="hacs"] {
    grid-column: 3 / 4;
  } 
 
  :host([expanded]) ha-md-list-item[tp="logs"] {
    grid-column: 4 / 5;
  } 
 
  :host([expanded]) ha-md-list-item[tp="logbook"] {
    grid-column: 1 / 2;
  } 
 
  :host([expanded]) ha-md-list-item[tp="history"] {
    grid-column: 2 / 3;
  } 
 
  :host([expanded]) ha-md-list-item[tp="dev-to"] {
    grid-column: 3 / 4;
  } 
 
  :host([expanded]) ha-md-list-item[tp="config"] {
    grid-column: 4 / 5;
  } 
```

The initial snippet (title & titleClick) turns the “Home Assistant” title into a clickable link that takes you to the main Lovelace dashboard.
Each element you want to shrink must have the tp attribute (I used to use panel, but the latest update removed it).
The grid-column fragment specifies which column the element should occupy.
If anyone runs into issues, I’m happy to help! :)

Cheers,
Valker :)

**Comment by elchininet** [comment]
Nice,
You should be able to convert this:

```css
  :host([expanded]) ha-md-list-item[tp="zigbee2mqtt"] > .item-text,
  :host([expanded]) ha-md-list-item[tp="nodered"] > .item-text,
  :host([expanded]) ha-md-list-item[tp="hacs"] > .item-text,
  :host([expanded]) ha-md-list-item[tp="logs"] > .item-text,
  :host([expanded]) ha-md-list-item[tp="logbook"] > .item-text,
  :host([expanded]) ha-md-list-item[tp="history"] > .item-text,
  :host([expanded]) ha-md-list-item[tp="dev-to"] > .item-text,
  :host([expanded]) ha-md-list-item[tp="config"] > .item-text
  {
    display: none !important;
  }
```

Into this (any item with the attribute `tp`):

```css
  :host([expanded]) ha-md-list-item[tp] > .item-text
  {
    display: none !important;
  }
```

And the next batch of styles in the `.item-text` should not have effect because the element is hidden, or does it serve other purpose?

**Reply by elchininet** [reply]
Post your approach in [the Custom Sidebar thread in the Community](https://community.home-assistant.io/t/custom-sidebar-manage-home-assistants-sidebar-items-per-user-or-device-basis/665800). I am sure that multiple users that do not read the discussions of the repo would find it interesting. 🙂

**Reply by eValker** [reply]
Hi,

You’re absolutely right :) Earlier, I was targeting elements using `data-panel` and because they didn’t share a common attribute, I had to target them individually. After the recent changes, I needed to find a new approach because `data-panel` disappeared, and due to the new structure, targeting by `a` tags became impossible/too complicated. Fortunately, I discovered the `attributes` configuration, which solved the problem and, in fact, introduced a common target attribute. However, I mindlessly changed the targeting approach and didn’t realize it could be done more optimally :)

As for the second styles configuration, it was indeed supposed to target the icon, which is now `ha-icon`, but I pasted something incorrectly. However, recent DOM structure change made it no longer necessary :) Visually it looked the same, so I didn’t notice it either. Nice catch :)

The corrected configuration now looks like this. It’s much better:

```yaml
id: main_sidebar
partials:
  titleClick: |
    window.titleClick = () => {
      const path = '/lovelace';
      window.history.replaceState(null, '', path);
      window.dispatchEvent(
        new CustomEvent(
          'location-changed',
          {
            detail: {
              replace: path
            }
          }
        )
      );
    };
    
title: |
  [[[
    @partial titleClick
    return '<span onClick="javascript:titleClick()" onTouchEnd="javascript:titleClick()" style="cursor:pointer;">Home Assistant</span>';
  ]]]
order:
# top
    
# bottom
  - item: dashboard-admin
    href: "/dashboard-admin"
    match: href
    bottom: true
    order: 9
  - item: 45df7312_zigbee2mqtt
    href: "/45df7312_zigbee2mqtt"
    match: href
    bottom: true
    order: 10
    attributes:
      tp: zigbee2mqtt
  - item: a0d7b954_nodered
    href: "/a0d7b954_nodered"
    match: href
    bottom: true
    order: 11
    attributes:
      tp: nodered
  - item: hacs
    href: "/hacs"
    match: href
    bottom: true
    order: 12
    attributes:
      tp: hacs
  - new_item: true
    match: href
    item: Logs
    href: "/config/logs"
    icon: mdi:math-log
    order: 13
    attributes:
      tp: logs
    bottom: true
  - item: logbook
    match: href
    bottom: true
    order: 14
    attributes:
      tp: logbook
  - item: history
    match: href
    bottom: true
    order: 15
    attributes:
      tp: history
  - item: developer-tools
    icon: mdi:dev-to
    match: href
    bottom: true
    order: 16
    attributes:
      tp: dev-to
  - item: config
    icon: mdi:tune
    match: href
    bottom: true
    order: 17
    attributes:
      tp: config
    
#hidden
  - item: lovelace
    match: href
    hide: true 
  - item: map
    hide: true
    match: href
  - item: media
    hide: true
    match: href
  - item: energy
    match: href
    hide: true
  - item: calendar
    match: href
    hide: true
  - item: todo
    match: href
    hide: false
        
styles: |
  :host([expanded]) ha-md-list {
    display: grid;
    grid-template-columns: repeat(4, 25%);
    grid-template-rows: auto 1fr auto;
  }
  
  :host([expanded]) ha-md-list > ha-md-list-item {
    grid-column: 1 / 5;
    height: 48px;
  }
  
  :host([expanded]) ha-md-list > ha-md-list-item[tp] {
    width: 48px;
  }

  :host([expanded]) ha-md-list-item[tp] > .item-text
  {
    display: none !important;
  }
 
  :host([expanded]) ha-md-list-item[tp="zigbee2mqtt"] {
    grid-column: 1 / 2;
  } 
 
  :host([expanded]) ha-md-list-item[tp="nodered"] {
    grid-column: 2 / 3;
  } 
 
  :host([expanded]) ha-md-list-item[tp="hacs"] {
    grid-column: 3 / 4;
  } 
 
  :host([expanded]) ha-md-list-item[tp="logs"] {
    grid-column: 4 / 5;
  } 
 
  :host([expanded]) ha-md-list-item[tp="logbook"] {
    grid-column: 1 / 2;
  } 
 
  :host([expanded]) ha-md-list-item[tp="history"] {
    grid-column: 2 / 3;
  } 
 
  :host([expanded]) ha-md-list-item[tp="dev-to"] {
    grid-column: 3 / 4;
  } 
 
  :host([expanded]) ha-md-list-item[tp="config"] {
    grid-column: 4 / 5;
  } 
```
