### DISCUSSION TITLE
IsAdmin extras

### DISCUSSION THREAD

**Discussion by Robovh** [elchininet/custom-sidebar#415] [Q&A]
So what I’m looking for is a way to have a default set of sidebar elements configured to be the same for all users. And show specific items only if the user is an admin. I have tried to do this with the exceptions but this only resulted in me copy pasting the default elements and adding the admin elements, since I else would ONLY have the admin elements. And since copy pasting is redundant and bad practice I came for some help. Anybody tips on how to make this happen?
I have the feeling that this is easily done, but that I’m just completely overlooking something 😅

Ps I did take a quick look for discussions on this topic but didn’t see one matching this. Please correct me if I’m wrong.

**Comment by elchininet** [comment]
Hi @Robovh,
You can set a default sidebar for everybody, create an exception for admins, and just [hide everything and show only the items for admins](https://elchininet.github.io/custom-sidebar/blog/how-to-start-with-an-empty-sidebar).

**Comment by Robovh** [comment]
Yes, I already used the hide_all feature, since I dont want to have lingering pages which have been newly added and want to add those at the propper location ect ect.
But I want the admin features to be on top of the default features, so for example:

```
# note, I removed some of the additional settings to make it shorter
order:
  - new_item: true     # this is only usefull for the admin
    item: info
    href: "/config/info"
    <shortend>

  - new_item: true     # this is only usefull for the admin
    item: Restart
    href: "developer-tools/yaml?shouldRestart=1"
    icon: mdi:refresh

  - item: /config     # this is only usefull for the admin
    name: Settings
    match: href
    exact: true
    hide: false
    <shortend>

  - item: /developer-tools     # this is only usefull for the admin
    name: Developer Tools
    match: href
    exact: true
    icon: mdi:tools
    hide: false

  - new_item: true
    item: Verlichting
    href: "/dashboard-home/lights"
    <shortend>

  - new_item: true
    item: Contact
    href: "/dashboard-home/contacts"
    <shortend>

  - new_item: true
    item: Camera
    href: "/dashboard-home/camera"
    <shortend>

  - new_item: true
    item: Motion
    href: "/dashboard-home/motion"
    <shortend>

  - new_item: true
    item: Afval
    href: "/dashboard-home/afvalwijzer"
    <shortend>
    divider: true

  # Dashboards
  - new_item: true
    item: Dashboards
    href: "/config/lovelace/dashboards"
    icon: mdi:monitor-dashboard
  - item: Rooms
    icon: mdi:floor-plan
    hide: false
  - item: Testboard
    icon: mdi:folder-star-multiple
    hide: false
    divider: true

  # Add-ons
  - new_item: true     # this is only usefull for the admin
    item: Add-ons
    href: "/hassio/dashboard"
    <shortend>
  - item: Studio Code Server     # this is only usefull for the admin
    hide: false
  - item: Zigbee2MQTT     # this is only usefull for the admin
    name: Zigbee
    hide: false
    <shortend>
  - item: Z-Wave JS     # this is only usefull for the admin
    name: Z-Wave
    hide: false
```

So basically I guess im looking for a forAdmin boolean on elements, so that I can make one generic layout (which would be the layout for the admin) and just hide admin elements for not admins.
Would something like this be possible?

**Reply by elchininet** [reply]
>So basically I guess im looking for a forAdmin boolean on elements, so that I can make one generic layout (which would be the layout for the admin) and just hide admin elements for not admins.
Would something like this be possible?

That is not needed. You have multiple options there.

### Using exceptions

Having an exception for admins

```yaml
order:
  ## Option for everyone
  - new_item: true
    item: Verlichting
    href: "/dashboard-home/lights"

  ## Option for everyone
  - new_item: true
    item: Contact
    href: "/dashboard-home/contacts"
exceptions:
  - is_admin: true
    extend_from: 'base' ## this makes the above options for everyone also available for admins
    order:
      ## This will be available only for admins
      - new_item: true
        item: info
        href: "/config/info"
        order: 1

      ## This change the order of the item in the main config
      - item: Verlichting
        order: 2

      ## This will be available only for admins
      - new_item: true
        item: Restart
        href: "developer-tools/yaml?shouldRestart=1"
        icon: mdi:refresh
        order: 3

      ## This change the order of the item in the main config
      - item: Contact
        order: 4
```

### Use templates to hide the items only for non admins

```yaml
order:
  ## Option for everyone
  - new_item: true
    item: Verlichting
    href: "/dashboard-home/lights"

  ## This will be available only for admins
  - new_item: true
    item: info
    href: "/config/info"
    hide: '[[[ !user_is_admin ]]]'

  ## Option for everyone
  - new_item: true
    item: Contact
    href: "/dashboard-home/contacts"

  ## This will be available only for admins
  - new_item: true
    item: Restart
    href: "developer-tools/yaml?shouldRestart=1"
    icon: mdi:refresh
    hide: '[[[ !user_is_admin ]]]'
```

Tip:

I am seeing that you have an option with this `href` `"developer-tools/yaml?shouldRestart=1"`. I don't know what is the purpose of that item, but if the purpose of that item is to restart `Home Assistant` having an item with [an open dialog action](https://elchininet.github.io/custom-sidebar/configuration/the-on-click-property#open-dialog-action) setting the `type` as `restart` will open the dialog to restart `Home Assistant`. Or if you want to restart only with one click, you can have [a call service action](https://elchininet.github.io/custom-sidebar/configuration/the-on-click-property#call-service-action) calling the service to restart `Home Assistant`.
