### DISCUSSION TITLE
Does it also work in the app?

### DISCUSSION THREAD

**Discussion by der8en** [elchininet/custom-sidebar#87] [Q&A] [answered]
Hello,
thank you very much for the great plugin.
I have created a sidebar-config.yaml and it works fine in the browser, but not in the (Android-) app.
Is the config wrong or what is the reason?

<details><summary> sidebar-config.yaml</summary>

```html
order:
  - item: lovelace
    match: data-panel
    order: 1
  - item: energy
    match: data-panel
    order: 2
  - item: todo
    match: data-panel
    order: 3
  - item: logbook
    match: data-panel
    hide: true
  - item: history
    match: data-panel
    hide: true
  - item: developer-tools
    match: data-panel
    bottom: true
    order: 6
  - item: config
    match: data-panel
    exact: true
    bottom: true
    order: 7
  - item: medien
    hide: true
sidebar_editable: false
exceptions:
  - user:
    - ben
    base_order: true
    order:
      - item: logbook
        match: data-panel
        order: 4
      - item: history
        match: data-panel
        order: 5
``` 

</details>

**Comment by elchininet** [comment]
Hi @der8en,
Yes, it should also work on the Android Companion App, i have it in an Android device. Please, post an screenshot of your sidebar in Android to see what you are trying to match with that configuration.
Regards

**Comment by der8en** [comment]
I just want to create a simplified sidebar for non-admin users.
Hide media, logbook and history.
<details><summary>Screenshots</summary>

![Screenshot_20240412_101238_Home Assistant](https://github.com/elchininet/custom-sidebar/assets/19150585/6911caaf-a20c-4628-91bf-9b72d4ab5d9b)
![Screenshot 2024-04-12 Desktop](https://github.com/elchininet/custom-sidebar/assets/19150585/61cde0b1-c2bd-43f6-82ad-b416797ba764)

</details>

**Reply by elchininet** [reply]
I am seeing that it is the same user and even the `base_order` is not taken into account.

Just create a basic configuration, go from simple to complex. Create a minimum configuration just hiding an item, for example. If you see that it doesn‘t work on the app, I would recommend to clean cache and data of the Companion App (you would need to login again) and check if that solves the issue, sometimes the caching system on the Companion App is very stubborn.

**Reply by elchininet** [reply]
If it still doesn‘t work for you, I‘ll try this afternoon with the YAML version on my mobile using a config similar to yours (I am using the JSON version). To see if something is different there.

**Reply by der8en** [reply]
I figured it out: as soon as you remove the developer tools section ~~(or move it to the admin user)~~ it works
I now have this config and it works:
<details><summary>sidebar-config.yaml </summary>

```
order:
  - item: lovelace
    match: data-panel
    order: 1
  - item: energy
    match: data-panel
    order: 2
  - item: todo
    match: data-panel
    order: 3
  - item: logbook
    match: data-panel
    hide: true
  - item: history
    match: data-panel
    hide: true
  - item: app-konfiguration
    bottom: true
    order: 6
  - item: config
    match: data-panel
    exact: true
    bottom: true
    order: 8
  - item: medien
    hide: true
sidebar_editable: false
exceptions:
  - user:
    - ben
    base_order: true
    order:
      - item: logbook
        match: data-panel
        order: 4
      - item: history
        match: data-panel
        order: 5
      - item: developer-tools
        match: data-panel
        bottom: true
        order: 7
```

</details>
