### ISSUE TITLE
cant hide an element (the HA default Overview)

### ISSUE THREAD

**Issue by Mariusthvdb** [elchininet/custom-sidebar#102]
to prevent loading all states in a new browser, the HA default Overview, or after having logged on after new login, I have a `/lovelace/initial` view which is saved  under my dashboards:

<img width="801" alt="Scherm­afbeelding 2024-06-17 om 15 34 48" src="https://github.com/elchininet/custom-sidebar/assets/33354141/6076c7cf-81f1-4cb1-ae5e-e911afd9f0e6">

Since it is the default HA dashboard, it is named 'Overzicht' in the sidebar here:
<img width="1108" alt="Scherm­afbeelding 2024-06-17 om 15 36 23" src="https://github.com/elchininet/custom-sidebar/assets/33354141/a9d93627-8bc9-4788-80ea-5f4c69643ab0">

somehow I can not get this to hide anymore (I want to do that, as I also have a manually edited Overzicht.

I have no idea why. could it be a user error, or would HA Frontend have changed something.([there's another closed issue](https://github.com/elchininet/custom-sidebar/issues/23#issuecomment-1911023593) here proving I had it hidden before...)

I can hide it when settings sidebar_editable to false, and hide it in the HA UI, but, the is per browser, and I want it to hide everywhere.

Of course, except when needed...

my yaml settings are:

```
title: >
  [[[ 'Rumah kami: ' + new Date(states('sensor.date_time_iso'))
      .toLocaleTimeString().slice(0, 5) ]]]
# sidebar_editable: true
order:
  - item: ui-overzicht
    match: data-panel
    order: 1
  - item: ui-data
    match: data-panel
    order: 2
  - item: ui-familie
    match: data-panel
    order: 3
  - item: ui-instellingen
    match: data-panel
    order: 4
  - item: ui-develop
    match: data-panel
    order: 5
  - item: /ui-cctv
    match: href
    order: 6
  - item: /energy
    match: href
    order: 7
  - item: ui-test
    match: data-panel
    order: 8
  - item: ui-configured
    match: data-panel
    order: 9
  - item: /logbook
    match: href
    hide: true

  - item: /lovelace/initial
    match: href
    hide: true

  - item: history
    match: data-panel
    hide: true
  - item: calendar
    match: data-panel
    hide: true
  - item: todo
    match: data-panel
    hide: true
  - item: media
    hide: true
  - item: resources
    hide: true
  - item: config
    match: data-panel
    exact: true
    hide: true
  - item: developer-tools
    match: data-panel
    hide: true
```

**Comment by Mariusthvdb** [comment]
right, so after having tried many options, I finally decided to writeup this issue.

figured to give this one more shot:
```
  - item: Overzicht
    match: text
    hide: true
```

knowing I could run into trouble because of my other Menu item with the same name, and it works.....

<img width="253" alt="Scherm­afbeelding 2024-06-17 om 15 46 29" src="https://github.com/elchininet/custom-sidebar/assets/33354141/70f53a24-6909-43b2-816a-be5ec4d3d4a8">

so.closing, happy customer, my apologies...

**Comment by elchininet** [comment]
Hi @Mariusthvdb,
You shoule be able to hide it using the `data-panel` property. Could you take an screenshot of the HTML of your items to see what could be happening there?
Regards

**Comment by Mariusthvdb** [comment]
this is the default HA item to be hidden:

<img width="1154" alt="Scherm­afbeelding 2024-06-18 om 15 40 32" src="https://github.com/elchininet/custom-sidebar/assets/33354141/b67795f1-278f-4600-84e5-e891c604f95c">


and this is the custom set Overzicht me u item I want as main dashboard view:

<img width="1173" alt="Scherm­afbeelding 2024-06-18 om 15 41 41" src="https://github.com/elchininet/custom-sidebar/assets/33354141/a63d6f4c-f53b-48a8-8047-4256c8e53368">

**Comment by elchininet** [comment]
Hi @Mariusthvdb,
That should be the issue, you can try with:

```yaml
- item: /lovelace
    match: href
    hide: true
```

Regards
