### ISSUE TITLE
Sidebar Configuration isn't actually doing anything?

### ISSUE THREAD

**Issue by silicon-academy** [elchininet/custom-sidebar#117]
I have installed via HACS, and added to configuration.yaml:
``` 
frontend:
  extra_module_url:
    - /hacsfiles/custom-sidebar/custom-sidebar-yaml.js?v4.6.0 
 ```

I've also added a file at /config/www/sidebar-config.yaml
```
title: Home Assistant
order:
  - item: overview
    order: 0
  - new_item: true
    item: Frigate
    href: "/ccab4aaf_frigate-proxy/ingress"
    icon: mdi:camera
    order: 1
  - new_item: true
    item: Energy
    # href: "/energy"
    icon: mdi:lightning-bolt
    order: 2
  - new_item: true
    item: Automations
    href: "/config/automation"
    icon: mdi:robot
    order: 3
  - item: history
    icon: mdi:history
    order: 4
  - item: hacs
    order: 5
    notification: '[[[ state_attr("sensor.hacs", "repositories").length || "" ]]]'
  - item: config
    bottom: true
    order: 6
  - new_item: true
    item: Server Controls
    href: "/config/server_control"
    icon: mdi:server
    bottom: true
    order: 7
  - item: logbook
    bottom: true
    order: 8
  - new_item: true
    item: Logs
    bottom: true
    href: "/config/logs"
    icon: mdi:math-log
    order: 9
  - item: developer tools
    name: Dev tools
    icon: mdi:tools
    bottom: true
    order: 10
  - item: snapshots
    hide: true
  - item: backups
    hide: true
  - item: map
    hide: true
  - item: energy
    hide: true
  - item: media browser
    hide: true
```

I've restarted HA, cleared cache, and reloaded yaml, but nothing seems to be happening, and the original sidebar is still there. Is there something I'm doing wrong? I appreciate your help in advance, and this seems like a great repo. I apologize if I'm missing something, or if my English is bad, as it's not my first language. Thanks!
