### ISSUE TITLE
Unable to get the custom-sidebar running

### ISSUE THREAD

**Issue by ilexpl01** [elchininet/custom-sidebar#122]
Hi,

I use dockerized HA. Installed custom-sidebar with HACS.

Added to my configuration.yaml:

_frontend:
  themes: !include_dir_merge_named themes
  extra_module_url:
    - /config/www/community/custom-sidebar/custom-sidebar-yaml.js?v4.6.0

Created a simple sidebar-config.yaml file in /config/www/ folder.

HA restarted and get an error:

![image](https://github.com/user-attachments/assets/7c712f15-ca05-4bad-ad3f-2de73a34274e)

any advice ?

**Comment by elchininet** [comment]
Hi @ilexpl01,
A front-end extra module should be publicly accesible by the host. If the `/hacsfiles` alias doesn't work in a Docker instance, try to set it up using the `/local` path:

```yaml
frontend:
  extra_module_url:
    - /local/community/custom-sidebar/custom-sidebar-yaml.js?v4.6.0
```

Regards
