### ISSUE TITLE
Companion App & Sidebar Items?

### ISSUE THREAD

**Issue by majorsl** [elchininet/custom-sidebar#130]
I installed custom-sidebar with a very simple configuration to test: hiding the media and energy items.

On a web browser, it works perfectly.  On the Android Companion App it doesn't seem to hide them.  Is this a limitation of HA and how it talks to the companion apps or do I need to add a specific device configuration to my yaml?

**Comment by elchininet** [comment]
Hi @majorsl,
There is no any limitation with the Android Companion App, I have it myself working without issues. You should be suffereing of a caching issue, try to clean the cache of the App, change the version of the `JavaScript` resource at the end of the URL and restart Home Assistant. If that doesn't work, I am affraid that [logging off and logging in again would be your last resource](https://github.com/elchininet/custom-sidebar/issues/117#issuecomment-2292609454).
Regards

**Comment by loocd** [comment]
I hope it's ok if I piggyback off this - I've set up the custom sidebar and all works perfectly on Desktop.

But for some reason nothing has changed in the android companion app (2024.7.3-full) (no new items, no name-changes, no reordering, nothing). I've tried deleting and re-adding the server, logging out and re-adding the server, changing the server, clearing the app cache, closing and reopening the app, changing the custom-sidebar version number in configuration.yaml.

I don't know what there is left to do ^^ any ideas?

**Comment by majorsl** [comment]
> Wait a second - I just tried one other thing.
> 
> I had this in my sidebar-config.yaml:
> 
> ```
>   - item: external-app-configuration
>     match: "data-panel"
>     bottom: true
> ```
> 
> after removing it, the sidebar loads correctly in the Android companion app. Seems that something about this is wrong and the app couldn't handle that?
> 
> Any idea how I can move the app configuration to the bottom? That's where it is by default, but as soon as I add custom-sidebar and add an element to bottom: true, the app-configuration element moves up

Actually, would you mind sharing your working config?  I still can't get it to work on my Android.

**Comment by loocd** [comment]
```
sidebar_editable: false
order:
  ###############
  # hide entries
  ###############
  - item: logbook
    match: "data-panel"
    exact: true
    hide: true
  - item: history
    match: "data-panel"
    exact: true
    hide: true
  - item: todo
    match: "data-panel"
    exact: true
    hide: true
  - item: media-browser
    match: "data-panel"
    exact: true
    hide: true
  - item: calendar
    match: "data-panel"
    exact: true
    hide: true
  ###############
  # rename
  ###############
  - item: lovelace
    match: "data-panel"
    exact: true
    name: "Dashboard"
    order: 1
  ###############
  # change order
  ###############
  - item: energy
    match: "data-panel"
    exact: true
    order: 2
```

**Comment by elchininet** [comment]
Hi @loocd,

I don't see any issue with this config that would make the App to break:

```yaml
- item: external-app-configuration
  match: "data-panel"
  bottom: true
```

The only thing is that it would not do anything (at least on my Home Assistant instance). In my case the Configuration is named `config` in its name and in its `data-panel` property.

<img width="1068" alt="image" src="https://github.com/user-attachments/assets/b7b7034e-a1cd-45af-8c05-0d71587ada31">

Just to let you both know how hard is the caching of Home Assistant. I was using the `JSON` package until some days ago that I decided to change to the `YAML` one. I edited the `extra_module_url` with the `YAML` one, removed the `JSON` config and added a `YAML` config. Everything worked properly on desktop but not in the Companion App, it showed the default sidebar. I cleaned cache in my Android phone, restarter Home Assistant, changed parameters in the `extra_module_url`, nothing worked, it was still showing the default sidebar. Then I decided to add the `JSON` config again and it started to work on my phone. So, Android was still loading the `JSON` module even if I changed it and restarted Home Assistant multiple times. 😕

By the way, this is my config so you can see how I moved the config to the bottom:

```yaml
---
title: My Home
sidebar_editable: false
order:
- item: overview
  name: Dashboard
  order: 0
- item: deconZ
  order: 1
- item: ESPHome
  order: 2
- item: HACS
  notification: |
    [[[
      const outdatedHacsEntities = Object.values(entities.update).filter(
        (entity) => entity.platform === 'hacs' && is_state(entity.entity_id, 'on')
      );
      return outdatedHacsEntities.length || '';
    ]]]
  order: 3
- item: logbook
  order: 4
- new_item: true
  item: Integrations
  href: "/config/integrations"
  icon: mdi:puzzle
  order: 5
- new_item: true
  item: Automations
  href: "/config/automation"
  icon: mdi:robot
  order: 6
- new_item: true
  item: Nginx Proxy Manager
  href: http://xxx.xxx.xxx.xxx
  target: _blank
  icon: mdi:arrow-decision
  order: 7
- new_item: true
  item: Backups
  href: "/hassio/backups"
  icon: mdi:backup-restore
  order: 8
- item: developer-tools
  match: data-panel
  bottom: true
  order: 9
- item: studio code
  bottom: true
- item: terminal
  bottom: true
- item: settings
  bottom: true
- item: energy
  hide: true
- item: map
  hide: true
- item: calendar
  hide: true
- item: phpMyAdmin
  hide: true
- item: media
  hide: true
- item: history
  hide: true
```

And this is how it is rendered on desktop and on the Android Companion App:

| Desktop | Android Companion App |
| ------- | --------------------- |
| ![image](https://github.com/user-attachments/assets/09e6f8e3-9ce1-4a00-a193-8fdcb8eff348) | ![image](https://github.com/user-attachments/assets/9d41683a-4e2f-4b5f-a004-2217b5894888) |
