### ISSUE TITLE
Exceptions with ver 5.0

### ISSUE THREAD

**Issue by ilexpl01** [elchininet/custom-sidebar#138]
Hi.

I still try to acomodate the plugin :)

according to guideline for newest version you can specify extend_from_base option for Exceptions 

Below is my sidebar-confonfig.yaml

title: Kopanka
sidebar_editable: true
order:
- new_item: true
  item: ESPHome
  href: http://xxx.xxx.xxx.xxx:6052
  target: _blank
  icon: mdi:arrow-decision
  order: 1
  exceptions:
  - user:
    - lukasz
    title: Murzyn
    extend_from_base: false
    sidebar_editable: false
    order:
      - item: energy
        hide: false

It shoul only display energy tab for "lukasz" logged user but he sees complete menu:

![image](https://github.com/user-attachments/assets/d044d39a-ab01-4b57-94df-38fd78366f36)

What do I do wrong ?

My goal is to allow user "lukasz" to have one and only one option in left sidebar,.

**Comment by elchininet** [comment]
Hi @ilexpl01,
First of all, I don't know if it is because you didn't chose a proper code block but watch out the syntax and the identation, in `yaml` code this is crucial. This should be your config (you don't need to specify `sidebar_editable` in `true`, it is `true` by default):

```yaml
title: Kopanka
sidebar_editable: true
order:
  - new_item: true
    item: ESPHome
    href: http://xxx.xxx.xxx.xxx:6052
    target: _blank
    icon: mdi:arrow-decision
    order: 1
exceptions:
  - user:
    - lukasz
    title: Murzyn
    extend_from_base: false
    sidebar_editable: false
    order:
      - item: energy
        hide: false
```

Secondly, you are trying to match an item called `energy` but as your language is not English, there is no `Energy` item in your sidebar, so either change `energy` to `energia` or try to use another matcher (`data-panel` or `href`).

And lastly, you missunderstood what `extend_from_base` does (you don't need to specify it if it is `false`, it is `false` by default, the same with the `hide` parameter on each item, it is `false` by default). From the documentation:

>Pay attention to extend_from_base property. If it's set to `false` (default value), the main `config` will be ignored, leaving you with default sidebar modified only by the exception's options

This means that if you put only one item in the exceptions and setting `hide` in the `energy` as `false`, you will end up with a default sidebar without changes. If you want to hide everything for that user excluding the `energy` tab, you need to set `hide` in true for everything excepting the energy one 🙂

Let me know how it goes.
