### ISSUE TITLE
5.0 example and up to date documentation?

### ISSUE THREAD

**Issue by rwzdoorn** [elchininet/custom-sidebar#141]
First off; thanks for reviving this add-on! 

I'm trying (and struggling) to get the custom sidebar up and running with version +5.0. 

I have this in my sidebar-config.yaml:

```
sidebar:
  - title: Overview
    icon: mdi:view-dashboard
    path: /lovelace/overview

  - title: Energy
    icon: mdi:flash
    path: /lovelace/energy

  - title: HACS
    icon: mdi:package-variant-closed
    path: /hacs/entry

  - title: Integrations
    icon: mdi:puzzle-outline
    path: /config/integrations

  - title: Entities
    icon: mdi:shape
    path: /config/entities

  - title: Automations
    icon: mdi:robot
    path: /config/automation

  - title: Terminal
    icon: mdi:console
    path: /hassio/ingress/core_terminal

  - title: Studio Code Server
    icon: mdi:code-braces
    path: /hassio/ingress/a0d7b954_vscode    

  # Items to be placed at the bottom of the sidebar
  - title: Developer Tools
    icon: mdi:tools
    path: /developer-tools
    bottom: true

  - title: Settings
    icon: mdi:cog
    path: /config
    bottom: true

```

For some reason the Integrations, Entities and Automations are not shown. 

Is it possible to update the documentation and example(s)?

**Comment by elchininet** [comment]
Hi @rwzdoorn,
That is not a valid configuration. It would be good that you download the example provided in the documentation and start over it.

Things that I am seeing that are not right:

1. The sidebar items should be inside `order` not inside `sidebar`
2. As it is mentioned in [the Configuration Notes](https://github.com/elchininet/custom-sidebar?tab=readme-ov-file#notes): `All items in config.order should have a unique item property`
3. `path` is not a valid property for an order item
4. `title` is not a valid property for an order item

Regards

**Comment by rwzdoorn** [comment]
Ok, I didn't do my job properly I guess. I checked out the sidebar-config.yaml and it works like a charm (ofcource). This one can be closed! 

ps; keep up the good work and thanks for replying quickly!

**Comment by elchininet** [comment]
@rwzdoorn,

>Ok, I didn't do my job properly I guess. I checked out the sidebar-config.yaml and it works like a charm (ofcource).

Glad to hear that you have solved it 👍

>For some reason my config Is not going to the bottom of the panel (between hats & dev tools.

Most probably it is ot matching the item (you can check if there is any warning in the console of your browser dev tools). But if it is that, it should be visible, could you make a screenshot of your sidebar?

**Comment by rwzdoorn** [comment]
Hi,

This is currently my sidebar:
<img width="246" alt="Screenshot 2024-09-13 at 18 44 12" src="https://github.com/user-attachments/assets/2b498691-e315-4d3b-be3b-52518dc995a1">

I want to move the settings at the bottom. Also, how do I press the Studio Code Server at the bottom?

**Comment by elchininet** [comment]
That is the issue, you are trying to match an item called `config` by its text and there is no any item with the text `config`.

You can either match by `data-panel`:

```yaml
order:
 ...

 - item: config
   match: data-panel
   order: 8
   bottom: true
```

Or to match by text:

```yaml
order:
 ...

 - item: settings
   order: 8
   bottom: true
```

For the `Studio Code Server` the easiest way is to match it by text:

```yaml
order:
 ...

 - item: studio code
   order: 9
   bottom: true
```
