### ISSUE TITLE
[FR] Force show narrow (or wide) sidebar

### ISSUE THREAD

**Issue by denisfrench** [elchininet/custom-sidebar#156]
Hello @elchininet; here's a feature request as suggested originally for the Kiosk Mode plugin (https://github.com/NemesisRE/kiosk-mode/issues/281#issuecomment-2386878453).

It would be helpful to have a simple way to force-show the narrow sidebar on devices with screens that may otherwise hide it completely by default (eg RPi touchscreen 800x480). 

There may be use cases where the wide sidebar is preferred. Ideally exceptions by user or device could be applied.

Thanks for your work on all these plugins! 🙂

**Comment by elchininet** [comment]
Hi @denisfrench,
Based on some quick tests that I did, that is achievable.
I'll try to see how to implement it. I'll let you know.
Regards

**Comment by elchininet** [comment]
Hi @denisfrench,
A new version of `custom-sidebar` [has been released](https://github.com/elchininet/custom-sidebar/releases/tag/v5.2.0). Please, test it on your side and report it back.
Regards

**Comment by denisfrench** [comment]
Hi @elchininet ; I've got this up and running and it is working great, thank you!

My only hurdle was that implementing ```sidebar_mode:``` within ```exceptions:``` still requires a non-empty ```order:``` within the base level for it to work. So I just moved one of the items that I was happy to apply globally to the base ```order:```.

The following works, but not if I don't have a base ```order:``` with something in it (regardless of ```extend_from_base:``` setting):
```
order:
  - item: map
    match: data-panel
    exact: true
    hide: true
exceptions:
  - user: rpi
    sidebar_mode: narrow
    sidebar_editable: false
    extend_from_base: true
    order:
      - item: overview
        hide: true
      - item: mobile
        hide: true
      # - item: map
        # match: data-panel
        # exact: true
        # hide: true
      - item: test
        hide: true
      - item: energy
        hide: true
      - item: logbook
        hide: true
      - item: history
        hide: true
      - item: calendar
        hide: true
      - item: file
        hide: true
      - item: hacs
        hide: true
      - item: terminal
        hide: true
      - item: esphome
        hide: true
      - item: node
        hide: true
      - item: media
        hide: true
      - item: developer
        hide: true
      - item: settings
        hide: true
```

The readme tells me that the base ```order:``` is required, so I'm not surprised. It's just not neccessary for my use case.

There might have been a problem if there wasn't an item that I was happy to apply globally. Really this is an issue with ```order:``` being mandatory at the base level even when only using ```exceptions:```, rather than the implementation of ```sidebar_mode:```.

Thanks for your work on this. I hope others too will find it useful 🙂
