### ISSUE TITLE
unknown variable 'const'

### ISSUE THREAD

**Issue by Mariusthvdb** [elchininet/custom-sidebar#207]
using a js_variable

```
date_time: sensor.date_time_iso
```

and 

```
partials:
  title: |
    const tijd = states(date_time);
```

to be able to use the following template in the title:

```
title: >
  [[[ @partial title
    'Rumah kami: ' + new Date( tijd )
      .toLocaleTimeString([],{hour:"numeric",minute:"2-digit"}); ]]]
```

results in

<img width="528" alt="Scherm­afbeelding 2024-11-15 om 10 01 12" src="https://github.com/user-attachments/assets/037910da-4cde-40a4-a112-badd5661f753">

no matter what I try that error remains.

I can only successfully do

```
title: >
  [[[ 'Rumah kami: ' + new Date(states('sensor.date_time_iso'))
      .toLocaleTimeString([],{hour:"numeric",minute:"2-digit"}); ]]]
```

to get what I want:

<img width="259" alt="Scherm­afbeelding 2024-11-15 om 10 02 37" src="https://github.com/user-attachments/assets/6301dd7e-6923-4c08-a4b0-decc125cb594">

I must be missing a crucial syntax, but cant spot it.

In the end I would have wanted the full js manipulation in the partial, so I could do

```
title: >
  [[[ 'Rumah kami: ' + tijd; ]]]
```

in the final title template....

**Comment by elchininet** [comment]
>no matter what I try that error remains.

Let me explain you what is happening there.

When you write:

```
[[[ states('sensor.date_time_iso') ]]]
```

That becomes in `JavaScript`:

```javascript
return states('sensor.date_time_iso');
```

The `return` statement is added automatically because there is no return statement in your code, and the code should always return something.

So, taking your code together with your partial it becomes:

```javascript
return const tijd = states(sensor.date_time_iso);
'Rumah kami: ' + new Date( tijd )
      .toLocaleTimeString([],{hour:"numeric",minute:"2-digit"});
```

And that syntax is wrong.

The `autoReturn` is useful for simple statements, like the one at the beginning. If the code that you are writing is complex using variables, you should write your return, so it is not added automatically. Just write this and you should not get any error:

```yaml
title: >
  [[[ @partial title
    return ('Rumah kami: ' + new Date( tijd )
      .toLocaleTimeString([],{hour:"numeric",minute:"2-digit"})); ]]]
```

**Comment by elchininet** [comment]
>In the end I would have wanted the full js manipulation in the partial, so I could do
    title: >
        [[[ 'Rumah kami: ' + tijd; ]]]

This should do the work:

```yaml
js_variables:
  date_time: sensor.date_time_iso
partials:
  title: |
    const tijd = states(date_time);
    const tijdStr = new Date( tijd )
      .toLocaleTimeString([], {hour:"numeric",minute:"2-digit"});
order:
  - item: something
    title: >
      [[[ @partial title
        return `Rumah kami: ${tijdStr}`; ]]]
       
```
