### ISSUE TITLE
item vs new_item

### ISSUE THREAD

**Issue by xstrex** [elchininet/custom-sidebar#229]
Thanks for putting all this together, just trying to get is going but having some issues, and noticing some inconsistencies, so wanted to ask. 

I've successfully loaded your module:
```yaml
frontend:
  themes: !include_dir_merge_named themes
  extra_module_url:
    - /hacsfiles/lovelace-card-mod/card-mod.js
    - /hacsfiles/custom-sidebar/custom-sidebar-yaml.js
 ```
The developer tools shows the module is loaded:
![image](https://github.com/user-attachments/assets/948f2d49-5c2f-4a16-a4d9-f98551e77862)

Yet produces an invalid configuration (which is good, we're half way there)! 
Now it states that `every item in an "order" array should have an "item" property`.
Which would imply the following:
```yaml
order:
  - item
  - item
  - item
```
_and your [documentation](https://github.com/elchininet/custom-sidebar?tab=readme-ov-file#order-items-properties) for the `order` array states that `item` is the only required field._

Yet the [example](https://raw.githubusercontent.com/elchininet/custom-sidebar/master/sidebar-config.yaml) you provide doesn't follow this standard, and instead allows for either `item` or `new_item`. Which per the developer console should throw an exception.. 

So, which is it? Does the `order` array require `item` or `new_item`? Because utilizing both isn't working. 

For reference here's my sidebar-config.yaml:
```yaml
order:
  - item: overview
    order: 0
  - item: servers
    order: 1
  - itme: maintenance
    order: 2
  - new_item: true
    item: Integrations
    href: "/config/integrations"
    icon: mdi:puzzle
    order: 3
  # - new_item: true
  #   item: Entities
  #   href: "/config/entities"
  #   icon: mdi:hexagon-multiple
  #   order: 3
  - new_item: true
    item: Automations
    href: "/config/automation"
    icon: mdi:robot
    order: 4
  - item: terminal
    order: 5
    bottom: true
  - item: hacs
    order: 6
    bottom: true
    notification: |
      [[[
        const outdatedHacsEntities = Object.values(entities.update).filter(
          (entity) => entity.platform === 'hacs' && is_state(entity.entity_id, 'on')
        );
        return outdatedHacsEntities.length || '';
      ]]]
  - item: config
    bottom: true
    order: 7
  - item: developer
    name: Dev tools
    icon: mdi:tools
    bottom: true
    order: 8
  - item: studio code server
    name: Code Server
    icon: mdi:microsoft-visual-studio-code
    bottom: true
    order: 9
  - item: logbook
    hide: true
  - item: history
    hide: true
  - item: snapshots
    hide: true
  - item: backups
    hide: true
  - item: map
    hide: true
  - item: energy
    hide: true
  - item: media
    hide: true
# exceptions:
#   - user:
#     - Jim Hawkins
#     - Long John Silver
#     extend_from_base: false
#     order:
#       - new_item: true
#         item: Updates
#         href: "/config/updates"
#         icon: mdi:update
#   - user: Palaus
#     extend_from_base: true
#     order:
#       - item: history
#         order: 12
#       - item: media
#         order: 13
# id: example_yaml (remove this from your config or replace with any other string)
```

Also, when using HassOS, how would someone link to the esphome container- for instance the link in my default sidebar points to `http://redacted.internal.host:8123/5c53de3b_esphome`, I suspect since it's a container the `5c53de3b_esphome` will change (unconfirmed). Studio code server is another example, just not sure how to reference it.
