### ISSUE TITLE
Detect whenever "logs" is pressed on the sidebar

### ISSUE THREAD

**Issue by iamthekings5** [elchininet/custom-sidebar#249]
Hi,

I am trying to get a notification count to show on the logs entry in my custom sidebar. I was able to get it to count using event triggers and a counter, but resetting the count is a problem as pressing the clear button on the logs page doesn't seem to register as an event of any kind.

As an alternative solution I was wondering if actions could be added to custom sidebar so that whenever I press logs it automatically resets the counter.

If you have any creative solutions to my problem please let me know as well, short of manually pressing a separate button.

**Comment by elchininet** [comment]
Hi @iamthekings5,
Share the code that you are using at the moment to see though code what you want to achieve and what you have achieved at the moment. Logs are stored in a physical file in your `config` folder, so I think that it should be possible to create a [template sensor](https://www.home-assistant.io/integrations/template/) that uses a action with [a shell_command](https://www.home-assistant.io/integrations/shell_command/) to read the data from the logs.
Regards

**Comment by iamthekings5** [comment]
Hi,
![image](https://github.com/user-attachments/assets/e203c1ee-f735-4fc8-a52d-ed0065b3cd9e)
I want to find a way to detect whenever "CLEAR" is pressed.

This is an item in sidebar-config.yaml
```
  - new_item: true
    item: Logs
    bottom: true
    href: "/config/logs"
    icon: mdi:math-log
    notification: |
      {% if states('counter.system_logs') | int != 0 %}
        {{ states('counter.system_logs') }}
      {% endif %}
    order: 11
```
This is an automation detecting whenever logs are added.
```
alias: New automation 3
description: ""
triggers:
  - trigger: event
    event_type: system_log_event
    context: {}
    id: Log Created
  - trigger: event
    event_type: call_service
    event_data:
      domain: system_log
      event: clear
    context: {}
    id: Logs Cleared
conditions: []
actions:
  - choose:
      - conditions:
          - condition: trigger
            id:
              - Log Created
        sequence:
          - action: counter.increment
            metadata: {}
            data: {}
            target:
              entity_id: counter.system_logs
      - conditions:
          - condition: trigger
            id:
              - Logs Cleared
        sequence:
          - action: counter.reset
            metadata: {}
            data: {}
            target:
              entity_id: counter.system_logs
mode: single
```
Essentially, a log gets added > the counter increases by 1 > the sidebar shows a notification count of 1

this is all intended. But I do not have a way to detect whenever I press "CLEAR", I want the counter to reset whenever I press "CLEAR" so that the sidebar does not show a notification.

**Comment by elchininet** [comment]
Now I understand what you want to achieve, you want to get that number from System Log integration. You have entries in your "New automation 3" to capture clearing the logs, that is just things that you are trying, but do not work, right?

**Comment by iamthekings5** [comment]
The information is displaying fine. The counter also successfully increases on every log event.

The issue is I want the counter to reset to 0 when I click "CLEAR".

**Comment by elchininet** [comment]
>The issue is I want the counter to reset to 0 when I click "CLEAR".

Let me repeat my question in another way:

Forget that you have `custom-sidebar` installed. Is your counter reset by your automation? Is your automation working? You have entries to detect when the event `call_service.system_log` is called with `clear`, is that working?

**Comment by elchininet** [comment]
>It is to do with the automation.

I noticed your edit late. OK, could yoy try to change the config to this and check the counter? not in the notification but just in the state in the developer tools. We can jump to the notification once your automation is working OK:

```yaml
- trigger: event
  event_type: call_service
  event_data:
    domain: system_log
    service: clear
  id: Logs Cleared
```
