### ISSUE TITLE
Rename only?

### ISSUE THREAD

**Issue by schumi2004** [elchininet/custom-sidebar#274]
Is it possible to only rename items?
I don't care about order just want 2 items to be renamed and keep their position.

What i configured now is this:

```
order:
  - item: 45df7312_zigbee2mqtt
    match: "data-panel"
    exact: true
    name: "Zigbee2MQTT #1"
  - item: 9336c2b0_zigbee2mqtt
    match: "data-panel"
    exact: true
    name: "Zigbee2MQTT #2"
```

This will place both items at the top of the sidebar but i preferred to keep them somewhere at the bottom like this:

![image](https://github.com/user-attachments/assets/c45a3a44-73fb-45b5-963f-35a020a19f44)

Is such thing possible or is the only solution to rebuild and manually order side bar in sidebar-config.yaml?
