### ISSUE TITLE
Home Assistant 2025.1 Ignores custom-sidebar commands

### ISSUE THREAD

**Issue by iAmRenzo** [elchininet/custom-sidebar#276]
I've hidden things like logbook, calendar, history, tasks but they are now unhidden after 2025.1 update. Didn't change anything in the configuration.

**Comment by elchininet** [comment]
Hi @iAmRenzo,
Please, check your browser console and let me know if you have any warning or error coming from the plugin.
Regards

**Comment by werbi64** [comment]
I have the same problem
I have this in my browser console :

NS_ERROR_NOT_IMPLEMENTED: Component returned failure code: 0x80004001 (NS_ERROR_NOT_IMPLEMENTED) [nsIAppStartup.secondsSinceLastOSRestart]
    _collectStartupConditionsTelemetry resource:///modules/BrowserGlue.sys.mjs:1900
    BG__onFirstWindowLoaded resource:///modules/BrowserGlue.sys.mjs:1961
    BG_observe resource:///modules/BrowserGlue.sys.mjs:1168
    _delayedStartup chrome://browser/content/browser-init.js:667

Regards

**Comment by elchininet** [comment]
@werbi64,
Those messages are not related to the plugin.

I have tested in the Docker demo with `2025.1.1` and everything looks good:

![image](https://github.com/user-attachments/assets/35447317-f0b5-47b3-8f0b-4955077d0806)

And even [the Nightly Beta tests](https://github.com/elchininet/custom-sidebar/actions/workflows/ha-beta-tests.yaml) that run agains the Home Assistant beta version (and which consist in 300 thorough tests) are working without errors.

**Comment by elchininet** [comment]
Hi @iAmRenzo and @werbi64,
Please, open your Home Assistant instance in a browser **with a very minimal configuration** and let me know if you get any error or warning in the console. To help you with your issue I need that you provide some information, otherwise it is impossible to guide you through the solution.
Regards

**Comment by ErikFontanel** [comment]
I experience the same with 2025.2. The Chrome browser console shows no errors, just the Custom Sidebar version (v8.2.0). Is there a way to access my HA instance with a very minimal configuration without removing/reinstalling everything?

**Comment by elchininet** [comment]
>Is there a way to access my HA instance with a very minimal configuration without removing/reinstalling everything?

Just make a copy of your configuration  and edit the original one with a simple configuration like title change, then start to add one by one pieces until you reach the offended part, then report it back.

**Comment by elchininet** [comment]
Hi @ErikFontanel,
Did you perform the test with a minimal configuration?

**Comment by ErikFontanel** [comment]
I haven't had the time yet. My configuration is already very minimal because I use the UI for pretty much everything, so I'm not sure if using a minimal configuration will show much differrence. I did notice that the mobile app does show the correct sidebar configuration btw.

**Comment by elchininet** [comment]
>My configuration is already very minimal because I use the UI for pretty much everything, so I'm not sure if using a minimal configuration will show much differrence.

Just to be sure, I am talking about the `custom-sidebar` configuration, not about the Home Assistant configuration. If your `custom-sidebar` configuration is already very minimal, please share it.

>I did notice that the mobile app does show the correct sidebar configuration btw.

It doesn't make much sense but I need to check your config to use it with the Docker demo and see if I can detect any issue there.

**Comment by elchininet** [comment]
Hi @ErikFontanel,
Could you share your `custom-sidebar` config?

**Comment by ErikFontanel** [comment]
Aha, I get you now.

```yaml
order:
  - item: Media
    hide: true
exceptions:
  - user:
    - alice
    - bob
    extend_from_base: true
    order:
      - item: Overview
        order: 1
      - item: iCloud3
        order: 99
      - item: Map
        hide: true
      - item: Energy
        hide: true
      - item: Logbook
        hide: true
      - item: History
        hide: true
      - item: HACS
        hide: true
      - item: Zigbee2MQTT
        hide: true
```

I realise now my configuration is wrong! The items that were hidden before are under the `exceptions` key while my username isn't `alice` or `bob`.  Oddly enough this configuration without issue prior to HA 2025.1 and seems to work fine in the mobile view still. 

Sorry for the confusion!
