### ISSUE TITLE
Cannot get Changes to Load

### ISSUE THREAD

**Issue by digital-grease** [elchininet/custom-sidebar#277]
After following the written documentation (using yaml setup), including both the configuration.yaml changes as well as creation and modification of sidebar-config.yaml, it seems like nothing changes after a restart/refresh. I even went and watched the tutorial video linked in the documentation, and can't find anything i've done wrong.

configuration.yaml lines:

```
frontend:
  themes: !include_dir_merge_named themes
  extra_module_url:
    - /config/www/community/custom-sidebar/custom-sidebar-yaml.js
```
    

sidebar-config.yaml:

```
title: Greenhouse
order:
  - item: overview
    order: 0
  - item: map
    order: 1
  - item: music assistant
    order: 2
  - item: terminal
    order: 5
  - item: hacs
    order: 6
  - item: config
    bottom: true
    order: 7
  - item: logbook
    bottom: true
    order: 9
  - item: developer tools
    name: Dev tools
    icon: mdi:tools
    bottom: true
    order: 11
  - item: z-wave js
    order: 12
  - item: history
    hide: true
  - item: snapshots
    hide: true
  - item: backups
    hide: true
  - item: energy
    hide: true
  - item: media
    hide: true
  - item: mobile
    hide: true
exceptions:
  - device:
      - Android
    order:
      - item: mobile
        order: 0
      - item: music assistant
        order: 1
      - item: z-wave js
        order: 2
```

Console shows this error:

```Failed to load ‘https://[myserver]/config/www/community/custom-sidebar/custom-sidebar-yaml.js’. A ServiceWorker intercepted the request and encountered an unexpected error.```

Sorry if i'm missing something obvious here.
