### ISSUE TITLE
bug: divider option has no effect

### ISSUE THREAD

**Issue by tho-myr** [elchininet/custom-sidebar#310]
```yaml
title: Home Assistant
subtitle: Smartes Heim
order:
  - item: Overview
    name: Dashboard
    order: 0
  - item: Devices
    icon: mdi:devices
    order: 1
    new_item: true
    href: "/config/devices"
    info: |
      {{states('sensor.devices')}} Devices
  - item: Automations
    icon: mdi:robot
    order: 2
    new_item: true
    href: "/config/automation"
    info: |
      {{ states.automation | selectattr('state', 'eq', 'off') | list | count }} inaktive |  {{ states.automation | selectattr('state', 'eq', 'on') | list | count }} aktive
  - item: Integrations
    icon: mdi:import
    order: 3
    new_item: true
    href: "/config/integrations"
    info: |
      {{states('sensor.devices')}} Devices | {{states('sensor.entities')}} Entities
    divider: true
  - item: Add-Ons
    icon: mdi:puzzle
    order: 4
    new_item: true
    href: /hassio
  - item: Areas, labels & zones
    icon: mdi:sofa
    order: 5
    new_item: true
    href: /config/areas
  - item: hacs
    order: 6
    notification: |
      [[[
        const outdatedHacsEntities = Object.values(entities.update).filter(
          (entity) => entity.platform === 'hacs' && is_state(entity.entity_id, 'on')
        );
        return outdatedHacsEntities.length || '';
      ]]]
  - item: Developer tools
    bottom: true
  - item: Settings
    bottom: true
```

i added the divider option to the `item: Integrations` but it shows nothing. i updated hacs addon to 8.5.0 and reloaded configuration & restarted home assistant and also the html shows no additional divider object so the divider color is probably not the problem. is there anything wrong with my yaml config?
