### ISSUE TITLE
settings for second user group not applied

### ISSUE THREAD

**Issue by gorischek** [elchininet/custom-sidebar#328]
Hi,
I'm sure I'm doing something wrong, but I cannot find what. The settings for users tablet and romy are working as expected. But the settings for user michael are ignored (e.g. browser mod is not hidden). Can you please help to fix it?

```
default_path: /dashboard-wohnung/0
order:
  - item: Wohnung
    order: 0
  - item: Energieversorgung
    order: 1
  - item: Wohnungssensoren
    order: 2
  - item: Home Assistent
    order: 3
    icon: mdi:home-assistant
  - item: Tablet
    order: 5
  - item: terminal
    order: 20
  - item: hacs
    order: 30
    notification: |
      [[[
        const outdatedHacsEntities = Object.values(entities.update).filter(
          (entity) => entity.platform === 'hacs' && is_state(entity.entity_id, 'on')
        );
        return outdatedHacsEntities.length || '';
      ]]]
  - item: Medien
    hide: true
  - item: Energie
    hide: true
  - item: Verlauf
    hide: true
  - item: Logbuch
    hide: true
  - item: Übersicht
    hide: true
exceptions:
  - user:
    - tablet
    - romy
    default_path: /dashboard-tablet/0
    order:
      - item: Wohnung
        order: 0
      - item: Energieversorgung
        order: 1
      - item: Wohnungssensoren
        order: 2
      - item: Tablet
        order: 5
      - item: terminal
        hide: true
      - item: hacs
        hide: true
      - item: config
        hide: true
      - item: developer tools
        hide: true
      - item: history
        hide: true
      - item: snapshots
        hide: true
      - item: backups
        hide: true
      - item: map
        hide: true
      - item: Medien
        hide: true
      - item: Energie
        hide: true
      - item: Verlauf
        hide: true
      - item: Logbuch
        hide: true
      - item: Übersicht
        hide: true
      - item: Browser Mod
        hide: true
  - user: 
    - michael
    default_path: /dashboard-wohnung/0
    order:
      - item: terminal
        hide: true
      - item: hacs
        hide: true
      - item: config
        hide: true
      - item: developer tools
        hide: true
      - item: Browser Mod
        hide: true
```
