### ISSUE TITLE
Cant hide media player

### ISSUE THREAD

**Issue by Jinx735** [elchininet/custom-sidebar#33]
Hey, im trying to hide the media player/browser, but i cant seem to get it right. The integration does work (tried it with the file you provided).
Here's my config
```
order:
  - item: media browser
    hide: true
exceptions:
  - user:
    - test
    base_order: false
    order: []
id: 
```

Any idea what i might have gotten wrong?
