### ISSUE TITLE
Help needed

### ISSUE THREAD

**Issue by JC38** [elchininet/custom-sidebar#354]
Hello,

I am trying to use this add-on for 1 day but I can't figure out where I am making mistakes.
First, I am trying to hide some items to people not admin, the line hide: '{{ @partial admin_active }}' doesn't have any impact.
I also tried many of the examples given by the exceptions like this one
exceptions:
  - is_admin: true
    not_device: 'iPhone'
    not_user: 'ElChiniNet'
    matchers_conditions: 'AND'
    order:
      item: 'dashboard'
      hide: true

But everytime I am trying to use any exceptions , the custom sidebar settings are not applied.
Can someone add an example regarding my code, I hope it will help me to understand where is my mistake. For example, hiding the map item if user is John Doe ?

Thanks for your help

Here is my code (sorry, I can't use the fenced code blocks, the Github preview rendering is not correct if I use them)
title: 'My Sidebar test'
icon_color_selected: 'var(--accent-color)'
#sidebar_editable: false
default_path: '/dashboard-test/0'
jinja_variables:
  admin_boolean: 'input_boolean.show_admin_sidebar_items'
partials:
  admin_active: '{{ is_state(admin_boolean, "on") }}'
order:
  - item: overview
    hide: true
    order: 0
  - item: Aperçu
    hide: true
    order: 0
  - item: Bureaux
    order: 1
    hide: '{{ @partial admin_active }}'
  - item: Equipements
    order: 2
  - item: Mon site
    hide: '{{ @partial admin_active }}'
    order: 4
  - item: Energ
    order: 5
  - item: Histo
    divider: true
    order: 6
  - item: Calen
    order: 7
    hide: '{{ @partial admin_active }}'
  - item: Media
    hide: '{{ @partial admin_active }}'
    divider: true
    order: 9
  - item: Médias
    hide: '{{ @partial admin_active }}'
    order: 9
  - item: HACS
    order: 10
    hide: '{{ @partial admin_active }}'
  - item: Viewer
    order: 11
    hide: '{{ @partial admin_active }}'
  - item: journal
    hide: '{{ @partial admin_active }}'
    order: 95
  - item: logbook
    hide: '{{ @partial admin_active }}'
    order: 95
  - item: File
    order: 96
    hide: '{{ @partial admin_active }}'
  - item: studio code server
    hide: '{{ @partial admin_active }}'
    order: 97
  - item: developer tools
    hide: '{{ @partial admin_active }}'
    order: 98
  - item: settings
    hide: '{{ @partial admin_active }}'
    order: 99
  - item: map
    hide: true
id: test_yaml

**Comment by JC38** [comment]
Hi @elchininet 

Thank you for your interest.
Yesterday, I've started with the minimal but once I wanted to start ordering and hiding some items, I've added all my items as if i don't, every is mixed and more difficult to check while debugging.

So, this morning, i tested this way regarding your answer :
`js_variables:
  admin_boolean: 'input_boolean.show_admin_sidebar_items'
partials:
  admin_active: 'const admin_active = is_state(admin_boolean, "on");'
order:
  - item: Equipements
    hide: |
      [[[
        @partial admin_active
        return admin_active;
      ]]]
`
Am i right that with such settings, a non administrator user should not see the item Equipements ?

**Comment by elchininet** [comment]
>Am i right that with such settings, a non administrator user should not see the item Equipements ?

No, with those settings you are only making that any user (regardless if they are admins or not) will be able to see that item when the state of the entity `input_boolean.show_admin_sidebar_items` is `on` and they will get that item hidden when the entity state is `off`.

**Comment by JC38** [comment]
Ok, so my misunderstanding was there. I was confused with the variable names.
So, I come back to my initial idea, hiding or not items regarding the user role admin (administrator  or normal user) or user names.
The built-in function into HA dashboard is working for hiding dashboards to non admin users but for items such media, I don't see how to do without using your add-on.

**Comment by JC38** [comment]
Thank you.
I first tried that 
```
order:
  - item: Equipements
    hide: true
exceptions:
  - is_admin: true
    order:
      - item: Equipements
        hide: false
```
It doesn't work as the title goes back to the default

But without using exceptions, your suggestion is working fine 
```
order:
  - item: Equipements
    hide: '[[[ !user_is_admin ]]]'
```

So, I really have a problem with the exceptions. Just in case, I am running the latest HA version.

So, now, I am displaying menu items regarding if the user is admin or not, but if I want to display or hide menu items regarding the users names, ie John1 Doe, John2 Doe, Jane Doe, what would be the best solution ?

**Comment by elchininet** [comment]
>It doesn't work as the title goes back to the default

If the title goes back to default, you should have an error in the browser console. Open the console and let me know the error that you are getting.

>But without using exceptions, your suggestion is working fine

Perfect

>So, I really have a problem with the exceptions. Just in case, I am running the latest HA version.

Yes, it is OK.

>So, now, I am displaying menu items regarding if the user is admin or not, but if I want to display or hide menu items regarding the users names, ie John1 Doe, John2 Doe, Jane Doe, what would be the best solution ?

The same, you can do it also with templates using the `user_name` variable or with exceptions. So, let's try to check what error you have first so you can follow the solution that best suits you.

**Comment by JC38** [comment]
I can't see any error but I am not very confortable with this tool :
From Firefox
![Image](https://github.com/user-attachments/assets/627063af-fb13-4d2a-9b26-74ce98d111d6)

From Edge
![Image](https://github.com/user-attachments/assets/6099adbb-fa69-434f-8488-c28ec38b7a8a)

For this both, the title was back to default

![Image](https://github.com/user-attachments/assets/e47b5088-898f-4e80-8bd9-5ca3330f4214)

**Comment by elchininet** [comment]
>I can't see any error but I am not very confortable with this tool 👍 

Post also your configuration, to check where the issue is.

>And without the exceptions added, I have these warnings, that are "normal" I think. As the hide feature is checking the localized item name, that's why I double some items into the yaml, one for the English language, the other for French
In English

You don't need to do that, if you match by `data-panel` you can make a single config without the necessity of duplicating everything. The text of the items is translated but the `data-panel` property remains in all the languages. Having duplicated items could bring multiple issues because the plugin is trying to generate a config using all of them.

**Comment by elchininet** [comment]
Also notice that in different browsers the plugin is informing being in different versions. This is clearly a cache issue. Follow the same recommendation [here](https://elchininet.github.io/custom-sidebar/troubleshooting/customisations-are-not-applied-remotely) to clear your cache.

**Comment by JC38** [comment]
Ok, I've started cleaning the yaml with the duplicated items. Now, only English items are present.
I've looked for an example into your doc about using data-panel but I didn't find any. Plz, can you provide an example, using match and data-panel. And how to get the data-panel value ?

**Comment by elchininet** [comment]
>Ok, I've started cleaning the yaml with the duplicated items. Now, only English items are present.

Paste your `config` when you have it cleaned (and also refresh the cache before making more changes).

>I've looked for an example into your doc about using data-panel but I didn't find any. Plz, can you provide an example, using match and data-panel.

Nothing special, you just need to add the `match` property with that value:

```yaml
order:
  - item: 'developer-tools'
    match: 'data-panel'
    hide: true
```

>And how to get the data-panel value?

In your browser, right click over the item that you want to inspect and click on `inspect`. When the HTML code appears just go to the `a` DOM element of that item and check its `data-panel` property (for example this is the code of the `Developer tools` item):

![Image](https://github.com/user-attachments/assets/80af75a8-7a3d-44da-a6b5-a27c184f666f)

**Comment by JC38** [comment]
Thanks. I'll check that later, hope during the week-end.
Thanks again for your time.

**Comment by JC38** [comment]
Hello, I think I am ok now regarding hiding items without taking care of the language. 
I have a doubt about hiding the overview, I am using match: href and lovelace as string item
The rendering is ok for an user but not for an admin (and I don't see any error into the browser dev console). The error is related to the exceptions, if I remove it, the admin menu is ok.

Here is my latest version : 
````
title: 'Test'
icon_color_selected: 'var(--accent-color)'
#sidebar_editable: false
default_path: '/dashboard-test/0'
order:
  - item: 'lovelace'
    match: 'href'
    order: 0
    hide: true
  - item: Bureaux
    order: 1
    hide: '[[[ !user_is_admin ]]]'
  - item: Ateliers
    order: 2
    hide: false
  - item: Equipements
    hide: true
    order: 3
  - item: Site Test
    hide: '[[[ !user_is_admin ]]]'
    order: 4
  - item: Energ
    order: 5
  - item: history
    match: 'data-panel'
    divider: true
    order: 6
  - item: calendar
    match: 'data-panel'
    order: 7
    hide: '[[[ !user_is_admin ]]]'
  - item: 'media-browser'
    match: 'data-panel'
    hide: '[[[ !user_is_admin ]]]'
    divider: true
    order: 9
  - item: 'hacs'
    match: 'data-panel'
    order: 10
    hide: '[[[ !user_is_admin ]]]'
  - item: Viewer
    order: 11
    hide: '[[[ !user_is_admin ]]]'
  - item: logbook
    match: 'data-panel'
    hide: '[[[ !user_is_admin ]]]'
    order: 95
  - item: File
    order: 96
    hide: '[[[ !user_is_admin ]]]'
  - item: studio code server
    hide: '[[[ !user_is_admin ]]]'
    order: 97
  - item: 'developer-tools'
    match: 'data-panel'
    hide: '[[[ !user_is_admin ]]]'
    order: 98
  - item: settings
    hide: '[[[ !user_is_admin ]]]'
    order: 99
  - item: map
    hide: true
exceptions:
  - is_admin: true
    order:
      - item: Equipements
        hide: false
id: test_yaml
````

**Comment by elchininet** [comment]
>I have a doubt about hiding the overview, I am using match: href and lovelace as string item

In your configuration example you are not hiding the item with the `lovelace` `href`.

>The rendering is ok for an user but not for an admin (and I don't see any error into the browser dev console).

What do you mean with "not OK"? What is the result that you are getting?

>The error is related to the exceptions, if I remove it, the admin menu is ok.

This increasingly sounds to [a caching issue case](https://github.com/elchininet/custom-sidebar/issues/357#issuecomment-2726072472). Please, follow [these instructions](https://elchininet.github.io/custom-sidebar/troubleshooting/customisations-are-not-applied-remotely) and make sure that you refresh at least three times with that checkbox checked before testing (logging-in in an incognito window is another way to check if you don't have caching issues).

**Comment by JC38** [comment]
About the code for the href with lovelace
````
order:
  - item: 'lovelace'
    match: 'href'
    order: 0
    hide: false
````
I see that

![Image](https://github.com/user-attachments/assets/8b5395da-c794-4b52-b62d-2fef95101097)

And with 
````
order:
  - item: 'lovelace'
    match: 'href'
    order: 0
    hide: true
````
I've got 

![Image](https://github.com/user-attachments/assets/71507abd-4465-47d7-b3ef-051adca4d8ea)

For the not ok, I've got the standard title, the order is not the one I set and the divider doesn't appear --> the config is ignored

![Image](https://github.com/user-attachments/assets/9d669fbb-a258-4d56-a7eb-26828e1e23c3)

I have tested from an Edge and Firefox inprivate window, but also from another VM which has never been used to connect to any HA before.
I also did you recommendation about clearing the cache

![Image](https://github.com/user-attachments/assets/edda35e4-2b1f-4218-8cd0-ce85d810ddd4)

**Comment by elchininet** [comment]
>About the code for the href with lovelace.

That seems OK, it gets hidden when you set ` hide: true

>For the not ok, I've got the standard title, the order is not the one I set and the divider doesn't appear --> the config is ignored

That keeps sounding as a symptom of caching issues. It doesn't make sense that the config "is ignored" if you set a random option and there are no errors. The plugin is full with errors/warnings if something fails.

>I also did you recommendation about clearing the cache

That is not what I recommended, you are using a hard refresh but that will not clear the workers cache. I recommend to check a checkbox in the network tab. [Check again the instructions](https://elchininet.github.io/custom-sidebar/troubleshooting/customisations-are-not-applied-remotely).

**Comment by JC38** [comment]
Maybe I was not clear about clearing... I also did that and reloaded the page many times.

![Image](https://github.com/user-attachments/assets/ac1972c9-6fb0-486b-ab6b-bdbe58ae9e2f)

And don't forget I've tested also from browsers in incognito mode and even from Windows sessions that were never used before to browse the HA site. From my opinion, I don't think we can keep the browser caching as an issue.

**Comment by elchininet** [comment]
>And don't forget I've tested also from browsers in incognito mode and even from Windows sessions that were never used before to browse the HA site. From my opinion, I don't think we can keep the browser caching as an issue.

Let's try something. With that same window open, you will see a search field, search for `sidebar-config`, right click on the first result and select `copy > copy as fetch`.

<img width="1018" alt="Image" src="https://github.com/user-attachments/assets/c00a3350-725d-4cde-aa2b-54beec10303c" />

Then go to the `console` tab and paste the code, it should be something like this:

```javascript
fetch("http://your-home-assistant-server/local/sidebar-config.yaml?hash=241d66b73953f", {
  "headers": {
    "sec-ch-ua": "\"Not:A-Brand\";v=\"24\", \"Chromium\";v=\"134\"",
    "sec-ch-ua-mobile": "?0",
    "sec-ch-ua-platform": "\"macOS\""
  },
  "referrer": "https://ha.ipwk.net/lovelace/home",
  "referrerPolicy": "same-origin",
  "body": null,
  "method": "GET",
  "mode": "cors",
  "credentials": "omit"
});
```

Then, remove the semicolon from the end, and add this:

```javascript
fetch("http://your-home-assistant-server/local/sidebar-config.yaml?hash=241d66b73953f", {
  "headers": {
    "sec-ch-ua": "\"Not:A-Brand\";v=\"24\", \"Chromium\";v=\"134\"",
    "sec-ch-ua-mobile": "?0",
    "sec-ch-ua-platform": "\"macOS\""
  },
  "referrer": "https://ha.ipwk.net/lovelace/home",
  "referrerPolicy": "same-origin",
  "body": null,
  "method": "GET",
  "mode": "cors",
  "credentials": "omit"
})
    .then(result => result.text())
    .then(yaml => console.log(yaml));
```

Press enter and you should get your config. Check the config to see if it has the changes. If it has the changes, I'll create a custom bundle for you with several `console.logs` to detect where the issue is.

**Comment by elchininet** [comment]
Try better this, it is easier and it does the same:

![Image](https://github.com/user-attachments/assets/fb2cc82f-a493-4054-9f24-0864577684ae)

**Comment by JC38** [comment]
Hello, 
Here is what I get :

![Image](https://github.com/user-attachments/assets/fdb599d7-ca1f-4c02-ac37-3e9aef9f6b5e)

And the pasted response

````
title: 'Test'
icon_color_selected: 'var(--accent-color)'
#sidebar_editable: false
default_path: '/dashboard-test/0'
order:
  - item: 'lovelace'
    match: 'href'
    order: 0
    hide: true
  - item: Bureaux
    order: 1
    hide: '[[[ !user_is_admin ]]]'
  - item: Ateliers
    order: 2
    hide: false
  - item: Equipements
    hide: true
    order: 3
  - item: Site
    hide: '[[[ !user_is_admin ]]]'
    order: 4
  - item: Energ
    order: 5
  - item: history
    match: 'data-panel'
    divider: true
    order: 6
  - item: calendar
    match: 'data-panel'
    order: 7
    hide: '[[[ !user_is_admin ]]]'
  - item: 'media-browser'
    match: 'data-panel'
    hide: '[[[ !user_is_admin ]]]'
    divider: true
    order: 9
  - item: 'hacs'
    match: 'data-panel'
    order: 10
    hide: '[[[ !user_is_admin ]]]'
  - item: Viewer
    order: 11
    hide: '[[[ !user_is_admin ]]]'
  - item: logbook
    match: 'data-panel'
    hide: '[[[ !user_is_admin ]]]'
    order: 95
  - item: File
    order: 96
    hide: '[[[ !user_is_admin ]]]'
  - item: studio code server
    hide: '[[[ !user_is_admin ]]]'
    order: 97
  - item: 'developer-tools'
    match: 'data-panel'
    hide: '[[[ !user_is_admin ]]]'
    order: 98
  - item: settings
    hide: '[[[ !user_is_admin ]]]'
    order: 99
  - item: map
    hide: true
exceptions:
  - is_admin: true
    order:
      - item: Equipements
        hide: false`
```

**Comment by JC38** [comment]
I don't want to add confusion to the confusion, but if you want I have here at home another H.A (the other is into another location, another network, nothing to do with mine at home).
If I set the sidebar-config.yaml here at home like that :
```
`title: 'Home'
icon_color_selected: 'var(--accent-color)'
#sidebar_editable: false
default_path: '/dashboard-equipements/0'
order:
  - item: overview
    hide: true
  - item: Mushroom
    order: 0
    hide: true
  - item: Equipements
    order: 1
exceptions:
  - is_admin: true
    order:
      - item: Mushroom
        hide: `false``
```
I have exactly the same problem as soon as I add the exceptions section.
Maybe I will go on debugging on my local HA, it is easier and faster for me.

**Comment by elchininet** [comment]
>Here is what I get :

Perfect, I'll create a custom bundle for you, you will need to uninstall the one installed through `HACS` and install it manually. I'll let you know when I have it ready.

**Comment by elchininet** [comment]
>I don't want to add confusion to the confusion, but if you want I have here at home another H.A (the other is into another location, another network, nothing to do with mine at home).
If I set the sidebar-config.yaml here at home like that :

>I have exactly the same problem as soon as I add the exceptions section.
>Maybe I will go on debugging on my local HA, it is easier and faster for me.

I'll create a custom bundle for you with a lot of `console.logs` so we can determine where the issue is using your setup.

An isolated way to check is the Docker Demo of this repo which is a fresh instance of Home Assistant and with only Custom Sidebar installed. But it is better to test this with your setup, because [there are an extensive amount of tests tests in place related to exceptions](https://github.com/elchininet/custom-sidebar/blob/master/tests/07%20-%20exceptions-options.spec.ts) that are not failing not only in every pull request or a merge to master, but also [every night](https://github.com/elchininet/custom-sidebar/actions/workflows/ha-beta-tests.yaml) against the beta version of Home Assistant that it is under development, that is why it is better to test this exactly in the system in which you are having the issue.

**Comment by elchininet** [comment]
Hi @JC38,
Let's start with this [one](https://gist.github.com/elchininet/8e835f2946bfcd87595eaea54be1a2d9). If all is OK with the debug logs, I will create a second bundle with more. But this is a starting point logging the process of loading the config and creating the final config with exceptions so we can detect in which part it fails.

Follow these steps:

1. Uninstall `custom-sidebar` from HACS
2. Install the custom bundle in [the gist](https://gist.github.com/elchininet/8e835f2946bfcd87595eaea54be1a2d9) (following [the manual installation](https://elchininet.github.io/custom-sidebar/installation#manual-installation))
3. Check the `Disable cache` checkbox in the Network tab and refresh two or three times until you see the bunch of `console.logs` in the console tab
4. It will be a lot of `console.logs`, do not worry if it is long but paste the results here and I'll take a look at it to see if I detect where the issue is

**Comment by JC38** [comment]
Hello,

Here is the output from the console :

```
`custom-sidebar-yaml.js?v1.0.0:600 Custom tests @JC38: Instantiating Custom Sidebar
custom-sidebar-yaml.js?v1.0.0:596 ≡ CUSTOM-SIDEBAR (YAML)v9.1.2
custom-sidebar-yaml.js?v1.0.0:600 Custom tests @JC38: HAQuerySelector Init
custom-sidebar-yaml.js?v1.0.0:600 Custom tests @JC38: HAQuerySelector panel loaded
custom-sidebar-yaml.js?v1.0.0:600 Custom tests @JC38: Custom Sidebar calling process...
custom-sidebar-yaml.js?v1.0.0:600 Custom tests @JC38: _process started...
custom-sidebar-yaml.js?v1.0.0:600 Custom tests @JC38: _process resolved
custom-sidebar-yaml.js?v1.0.0:5944 <home-assistant style=​"direction:​ ltr;​ --direction:​ ltr;​ --float-start:​ left;​ --float-end:​ right;​ --margin-title:​ var(--margin-title-ltr)​;​ --scale-direction:​ 1;​">​…​</home-assistant>​
custom-sidebar-yaml.js?v1.0.0:600 Custom tests @JC38: starting HomeAssistantJavaScriptTemplates renderer
custom-sidebar-yaml.js?v1.0.0:600 Custom tests @JC38: Fetch response has been received
custom-sidebar-yaml.js?v1.0.0:600 Custom tests @JC38: Fetch response is OK
custom-sidebar-yaml.js?v1.0.0:600 Custom tests @JC38: HomeAssistantJavaScriptTemplates renderer resolved
custom-sidebar-yaml.js?v1.0.0:600 Custom tests @JC38: Getting the config...
custom-sidebar-yaml.js?v1.0.0:600 Custom tests @JC38: Starting getting the config...
custom-sidebar-yaml.js?v1.0.0:600 Custom tests @JC38: Raw YAML is:
custom-sidebar-yaml.js?v1.0.0:4988 title: 'Home'
icon_color_selected: 'var(--accent-color)'
#sidebar_editable: false
default_path: '/dashboard-equipements/0'
order:
  - item: overview
    hide: true
  - item: Mushroom
    order: 0
    hide: true
  - item: Equipements
    order: 1
exceptions:
  - is_admin: true
    order:
      - item: Mushroom
        hide: false
custom-sidebar-yaml.js?v1.0.0:600 Custom tests @JC38: End of raw YAML
custom-sidebar-yaml.js?v1.0.0:600 Custom tests @JC38: JSON config is:
custom-sidebar-yaml.js?v1.0.0:4995 {title: 'Home', icon_color_selected: 'var(--accent-color)', default_path: '/dashboard-equipements/0', order: Array(3), exceptions: Array(1)}
custom-sidebar-yaml.js?v1.0.0:600 Custom tests @JC38: End of JSON config
custom-sidebar-yaml.js?v1.0.0:600 Custom tests @JC38: Config has been validated
custom-sidebar-yaml.js?v1.0.0:600 Custom tests @JC38: Raw config:
custom-sidebar-yaml.js?v1.0.0:5082 {title: 'Home', icon_color_selected: 'var(--accent-color)', default_path: '/dashboard-equipements/0', order: Array(3), exceptions: Array(1)}
custom-sidebar-yaml.js?v1.0.0:600 Custom tests @JC38: End raw config:
custom-sidebar-yaml.js?v1.0.0:360 Custom tests @JC38: Instantiating ConfigFlatter
custom-sidebar-yaml.js?v1.0.0:360 Custom tests @JC38: Getting exceptions
custom-sidebar-yaml.js?v1.0.0:360 Custom tests @JC38: There are exceptions
custom-sidebar-yaml.js?v1.0.0:360 Custom tests @JC38: Exceptions:
custom-sidebar-yaml.js?v1.0.0:389 [{…}]
custom-sidebar-yaml.js?v1.0.0:360 Custom tests @JC38: End exceptions
custom-sidebar-yaml.js?v1.0.0:360 Custom tests @JC38: Creating flatten config with exceptions...
custom-sidebar-yaml.js?v1.0.0:360 Custom tests @JC38: Base options:
custom-sidebar-yaml.js?v1.0.0:471 {}
custom-sidebar-yaml.js?v1.0.0:360 Custom tests @JC38: End base options:
custom-sidebar-yaml.js?v1.0.0:360 Custom tests @JC38: Flatten config with exceptions:
custom-sidebar-yaml.js?v1.0.0:480 {order: Array(1), is_admin: true}
custom-sidebar-yaml.js?v1.0.0:360 Custom tests @JC38: End flatten config with exceptions
custom-sidebar-yaml.js?v1.0.0:360 Custom tests @JC38: ConfigFlatter.config:
custom-sidebar-yaml.js?v1.0.0:560 {order: Array(1), is_admin: true}
custom-sidebar-yaml.js?v1.0.0:360 Custom tests @JC38: End ConfigFlatter.config
custom-sidebar-yaml.js?v1.0.0:600 Custom tests @JC38: HAQuerySelector panel loaded
custom-sidebar-yaml.js?v1.0.0:600 Custom tests @JC38: HAQuerySelector panel loaded
```

**Comment by elchininet** [comment]
Everything seems OK but I cannot see the objects that are logged. I'll submit a second version to see the content of the objects.

**Comment by elchininet** [comment]
Hi @JC38,
Download [the latest gist](https://gist.github.com/elchininet/8e835f2946bfcd87595eaea54be1a2d9), follow the same steps and post the results.

**Comment by JC38** [comment]
```
custom-sidebar-yaml.js?v1.0.0:4 Custom tests @JC38: Instantiating Custom Sidebar
custom-sidebar-yaml.js?v1.0.0:4 ≡ CUSTOM-SIDEBAR (YAML)v9.1.2
custom-sidebar-yaml.js?v1.0.0:4 Custom tests @JC38: HAQuerySelector Init
custom-sidebar-yaml.js?v1.0.0:4 Custom tests @JC38: HAQuerySelector panel loaded
custom-sidebar-yaml.js?v1.0.0:4 Custom tests @JC38: Custom Sidebar calling process...
custom-sidebar-yaml.js?v1.0.0:4 Custom tests @JC38: _process started...
custom-sidebar-yaml.js?v1.0.0:4 Custom tests @JC38: _process resolved
custom-sidebar-yaml.js?v1.0.0:4 <home-assistant style=​"direction:​ ltr;​ --direction:​ ltr;​ --float-start:​ left;​ --float-end:​ right;​ --margin-title:​ var(--margin-title-ltr)​;​ --scale-direction:​ 1;​">​#shadow-root (open)</home-assistant>​
custom-sidebar-yaml.js?v1.0.0:4 Custom tests @JC38: starting HomeAssistantJavaScriptTemplates renderer
custom-sidebar-yaml.js?v1.0.0:4 Custom tests @JC38: Fetch response has been received
custom-sidebar-yaml.js?v1.0.0:4 Custom tests @JC38: Fetch response is OK
custom-sidebar-yaml.js?v1.0.0:4 Custom tests @JC38: Raw YAML is:
custom-sidebar-yaml.js?v1.0.0:4 "title: 'Home'\nicon_color_selected: 'var(--accent-color)'\n#sidebar_editable: false\ndefault_path: '/dashboard-equipements/0'\norder:\n  - item: overview\n    hide: true\n  - item: Mushroom\n    order: 0\n    hide: true\n  - item: Equipements\n    order: 1\nexceptions:\n  - is_admin: true\n    order:\n      - item: Mushroom\n        hide: false"
custom-sidebar-yaml.js?v1.0.0:4 Custom tests @JC38: End of raw YAML
custom-sidebar-yaml.js?v1.0.0:4 Custom tests @JC38: JSON config is:
custom-sidebar-yaml.js?v1.0.0:4 {
    "title": "Home",
    "icon_color_selected": "var(--accent-color)",
    "default_path": "/dashboard-equipements/0",
    "order": [
        {
            "item": "overview",
            "hide": true
        },
        {
            "item": "Mushroom",
            "order": 0,
            "hide": true
        },
        {
            "item": "Equipements",
            "order": 1
        }
    ],
    "exceptions": [
        {
            "is_admin": true,
            "order": [
                {
                    "item": "Mushroom",
                    "hide": false
                }
            ]
        }
    ]
}
custom-sidebar-yaml.js?v1.0.0:4 Custom tests @JC38: End of JSON config
custom-sidebar-yaml.js?v1.0.0:4 Custom tests @JC38: Config has been validated
custom-sidebar-yaml.js?v1.0.0:4 Custom tests @JC38: HomeAssistantJavaScriptTemplates renderer resolved
custom-sidebar-yaml.js?v1.0.0:4 Custom tests @JC38: Getting the config...
custom-sidebar-yaml.js?v1.0.0:4 Custom tests @JC38: Starting getting the config...
custom-sidebar-yaml.js?v1.0.0:4 Custom tests @JC38: Raw config:
custom-sidebar-yaml.js?v1.0.0:4 {
    "title": "Home",
    "icon_color_selected": "var(--accent-color)",
    "default_path": "/dashboard-equipements/0",
    "order": [
        {
            "item": "overview",
            "hide": true
        },
        {
            "item": "Mushroom",
            "order": 0,
            "hide": true
        },
        {
            "item": "Equipements",
            "order": 1
        }
    ],
    "exceptions": [
        {
            "is_admin": true,
            "order": [
                {
                    "item": "Mushroom",
                    "hide": false
                }
            ]
        }
    ]
}
custom-sidebar-yaml.js?v1.0.0:4 Custom tests @JC38: End raw config:
custom-sidebar-yaml.js?v1.0.0:4 Custom tests @JC38: Instantiating ConfigFlatter
custom-sidebar-yaml.js?v1.0.0:4 Custom tests @JC38: Getting exceptions
custom-sidebar-yaml.js?v1.0.0:4 Custom tests @JC38: There are exceptions
custom-sidebar-yaml.js?v1.0.0:4 Custom tests @JC38: Exceptions:
custom-sidebar-yaml.js?v1.0.0:4 [
    {
        "is_admin": true,
        "order": [
            {
                "item": "Mushroom",
                "hide": false
            }
        ]
    }
]
custom-sidebar-yaml.js?v1.0.0:4 Custom tests @JC38: End exceptions
custom-sidebar-yaml.js?v1.0.0:4 Custom tests @JC38: Creating flatten config with exceptions...
custom-sidebar-yaml.js?v1.0.0:4 Custom tests @JC38: Base options:
custom-sidebar-yaml.js?v1.0.0:4 {}
custom-sidebar-yaml.js?v1.0.0:4 Custom tests @JC38: End base options:
custom-sidebar-yaml.js?v1.0.0:4 Custom tests @JC38: Flatten config with exceptions:
custom-sidebar-yaml.js?v1.0.0:4 {
    "order": [
        {
            "item": "Mushroom",
            "hide": false
        }
    ],
    "is_admin": true
}
custom-sidebar-yaml.js?v1.0.0:4 Custom tests @JC38: End flatten config with exceptions
custom-sidebar-yaml.js?v1.0.0:4 Custom tests @JC38: ConfigFlatter.config:
custom-sidebar-yaml.js?v1.0.0:4 {
    "order": [
        {
            "item": "Mushroom",
            "hide": false
        }
    ],
    "is_admin": true
}
custom-sidebar-yaml.js?v1.0.0:4 Custom tests @JC38: End ConfigFlatter.config
custom-sidebar-yaml.js?v1.0.0:4 Custom tests @JC38: Config retrieved, continue...
custom-sidebar-yaml.js?v1.0.0:4 Custom tests @JC38: Processing default path...
custom-sidebar-yaml.js?v1.0.0:4 Custom tests @JC38: Processing the sidebar...
custom-sidebar-yaml.js?v1.0.0:4 Custom tests @JC38: Resolved panel resolved
custom-sidebar-yaml.js?v1.0.0:4 Custom tests @JC38: Resolved sidebar
custom-sidebar-yaml.js?v1.0.0:4 Custom tests @JC38: Styles added...
custom-sidebar-yaml.js?v1.0.0:4 Custom tests @JC38: ??? Subscription resolved...
custom-sidebar-yaml.js?v1.0.0:4 Custom tests @JC38: HAQuerySelector panel loaded
custom-sidebar-yaml.js?v1.0.0:4 Custom tests @JC38: HAQuerySelector panel loaded

```

**Comment by elchininet** [comment]
Perfect, let try to put that config in the Docker Demo to reproduce that log trace.

**Comment by elchininet** [comment]
@JC38,
Are you an `admin`?

**Comment by elchininet** [comment]
>No I am the owner on both systems.
>But i've just tested an admin account (not the owner one), and the issue is still there.
I started with the blue one and since you asked if i was an admin, i am testing with the yellow one. just in case.

Yes, the owner of a system is also an `admin`, so if you set `is_admin` it will also target the owner and the rest of admins.

Looking at the logs I don't see any issue, but I think that I understand what is happening and I think that it is only a misunderstanding. What you are expecting with the next configuration is to get the `title` and the other configurations from the base when you are an admin?

```yaml
title: 'Home'
icon_color_selected: 'var(--accent-color)'
#sidebar_editable: false
default_path: '/dashboard-equipements/0'
order:
  - item: overview
    hide: true
  - item: Mushroom
    order: 0
    hide: true
  - item: Equipements
    order: 1
exceptions:
  - is_admin: true
    order:
      - item: Mushroom
        hide: false
```

**Comment by JC38** [comment]
Yes. That's what I was thinking.

**Comment by elchininet** [comment]
>Yes. That's what I was thinking.

Sorry for misunderstanding your issue since the beginning, I understood something totally different. It was not needed all the custom bundle and debug that we did.

You will not get the base configuration automatically if you create an exception without extending the configuration from the base. Exceptions are basically a new configuration. In the previous configuration you are creating a configuration for non-admins an another one for admins (which does not have `title`, `icon_color_selected`, `default_path` or the other items inside the `order` array).

Check the last bullet point in the important section of the [exceptions section](https://elchininet.github.io/custom-sidebar/configuration/exceptions).

![Image](https://github.com/user-attachments/assets/baff6138-948a-41b8-89d0-d2f22cf944c2)

So, basically, to achieve what you are expecting you need to do:

```yaml
title: 'Home'
icon_color_selected: 'var(--accent-color)'
default_path: '/dashboard-equipements/0'
order:
  - item: overview
    hide: true
  - item: Mushroom
    order: 0
    hide: true
  - item: Equipements
    order: 1
exceptions:
  - is_admin: true
    # The next option will bring the options in the base to this exception
    extend_from: 'base'
    order:
      - item: Mushroom
        hide: false
```

You can also consult [this section](https://elchininet.github.io/custom-sidebar/advanced-configuration-options/extendable-configurations) in the documentation which explains how extendable configurations work and there is a section that explains the behaviour with `exceptions`.

**Comment by JC38** [comment]
Hello, 
The extend_from: 'base' did what I though. 
Ideally, what I would like, for non-admin users, is to show or not some items
Item1 , hidden for John and Jane but not for Jack
Item2, hidden for Jane and not for the others

Thanks again for your time, sorry for the misunderstanding.

**Comment by elchininet** [comment]
>Hello,
>The extend_from: 'base' did what I though.

Perfect, glad to hear that.

>Ideally, what I would like, for non-admin users, is to show or not some items
>Item1 , hidden for John and Jane but not for Jack
>Item2, hidden for Jane and not for the others

Just a note: if you target user names, it doesn't matter their access levels. If you target the user `Bill` you don't need to specify that it is not an admin, because it is impossible to have two `Bills` one admin and another one non-admin. It is enough if you specify the user's name.

You can achieve that using the same approach: templates or exceptions. With templates you have more freedom because you can write your own logic.

For the "Item1", you don't need to specify `Jack` because `Jack` is not included in the group for what you are hiding the item in the first instance. If you say that the `Item1` will be hidden for `John` and `Jane`, it will be hidden only for them and it will be visible for the rest (including `Jack`). It would make sense if you say for example _"Hidden for all admins excluding `Jack`"_ or _"Hidden for all Android devices except if the device is being used by `Jack`"_.

So, taking this into account you can do something like this:

### Templates

```yaml
order:
  - item: 'Item1'
    hide: |
      [[[ return (user_name === 'John' || user_name === 'Jane'); ]]]
  - item: 'Item2'
    hide: |
      [[[ return user_name === 'Jane' ]]]
``` 

### Exceptions

```yaml
exceptions:
  - user:
      - 'John'
      - 'Jane'
    order:
      - item: 'Item1'
        hide: true
  - user: 'Jane'
    order:
      - item: 'Item2'
        hide: true
```

>Thanks again for your time, sorry for the misunderstanding.

Do not worry, the misunderstanding was on my side because I assumed that you knew about how the `exceptions` were extended, and knowing it you were referring that the `title` was not available even in the configuration in which it was configured.
