### ISSUE TITLE
Add "Restart" Button to Side Bar

### ISSUE THREAD

**Issue by lich2000117** [elchininet/custom-sidebar#366]
Amazing work!!

I wonder has anyone done some quick config on a button to "Restart" HomeAssistant, or simply executing a bash script on the side bar? That would be cool to automate things in one click.

Thanks!

**Comment by lich2000117** [comment]
> Hi [@lich2000117](https://github.com/lich2000117),
> 
> You can add [a service call](https://elchininet.github.io/custom-sidebar/blog/execute-services-clicking-on-sidebar-items) to a sidebar item.

Thank you! didn't read the doc carefully

**Comment by elchininet** [comment]
Hi @lich2000117,
I don't know if you have followed the latest update. But now it is possible to do [this](https://elchininet.github.io/custom-sidebar/configuration/the-on-click-property#open-dialog-action):

```yaml
order:
  - new_item: true
    item: 'Restart'
    icon: 'mdi:restart'
    on_click:
      action: 'open-dialog'
      type: 'restart'
```

This will open the regular restart dialog of `Home Assistant`.
