### ISSUE TITLE
Custom Sidebar is broken in Home Assistant 2025.5.0

### ISSUE THREAD

**Issue by elchininet** [elchininet/custom-sidebar#399]
## Update

This issue has been solved in [the major version 10.0.0](https://github.com/elchininet/custom-sidebar/releases/tag/v10.0.0). Read the instructions before update. I'll let this issue open as a second filter wall for those that updated to the major version without being updated Home Assistant.

---

In Home Assistant `2025.5.0`, [the sidebar has been replaced entirely](https://github.com/home-assistant/frontend/pull/24883). This means that not only elements have changed their name, but also their location in the DOM tree. For this reason, the library will require an entire refactor that will potentially be a breaking change in its API.

If you want to keep using `Custom Sidebar`, you need to avoid updating Home Assistant to version `2025.5.0` until a new major version is released. I'll be updating about the progress in this issue.

Keep posted.

**Comment by jkosharek** [comment]
This is a bummer. Will issue #399 be the communication point for a new version release?

**Comment by elchininet** [comment]
>This is a bummer. Will issue https://github.com/elchininet/custom-sidebar/issues/399 be the communication point for a new version release?

That's right and that will be occurring in a few minutes.

**Comment by elchininet** [comment]
@jkosharek,
The communication has been made as an edit of the main issue.

**Comment by jkosharek** [comment]
My previous config items looked like this:
```
order:
  - new_item: true
    item: File Editor
    href: "/hassio/ingress/core_configurator"
    icon: mdi:book-edit-outline
    order: 1
  - new_item: true
    item: HA Editor
    href: "/ha-data-editor"
    icon: mdi:book-edit-outline
    order: 2
```
and from what I see in the browser dev tools that is the correct href, but none of the items are showing in the side bar.
