### ISSUE TITLE
Sidebar is still broken with JS errors

### ISSUE THREAD

**Issue by corgan2222** [elchininet/custom-sidebar#418]
After updating HA to Core 2025.4.4 & Frontend 20250411.0 and [custom-sidebar](https://github.com/elchininet/custom-sidebar) to 10.2.0 it stop working.
The JS is loaded, and the title is working, but throws errors.
I tried the yaml and the json version, the result is the same. I also deleted and completely reinstalled it. I cleared the cache a hundred times.

![Image](https://github.com/user-attachments/assets/9243c1ce-1f74-4b01-b829-8115214e0432)

See [error_log.log](https://github.com/user-attachments/files/20260819/error_log.log)

Configuration.yaml
```
# Load frontend themes from the themes folder
frontend:
  themes: !include_dir_merge_named themes
  extra_module_url:
    - /local/community/custom-brand-icons/custom-brand-icons.js
    - /hacsfiles/custom-sidebar/custom-sidebar-json.js
```

sidbar-config.json copied from documentation
```
{
    "title": "My Home2",
    "order": [
      {
        "new_item": true,
        "item": "Automations",
        "href": "/config/automation",
        "icon": "mdi:robot",
        "order": 1
      },
      {
        "item": "overview",
        "hide": true
      }
    ]
  }
```

any Ideas?
