### ISSUE TITLE
sidebar_mode narrow messes up dashboard header in compagnion app

### ISSUE THREAD

**Issue by HomeAssistantPim** [elchininet/custom-sidebar#431]
If you set sidebar_mode to narrow, the menu button is shown in dashboard header as well on the compagnion app (android).

workaround is to set the sidebar_mode only for specific devices
```
exceptions:
  - not_device:
    - iphone
    - android
    extend_from: base
    sidebar_mode: narrow    
```
