### ISSUE TITLE
`bottom: true` flag doesn't seem to work on most items

### ISSUE THREAD

**Issue by akshay7394** [elchininet/custom-sidebar#73]
The `bottom: true` flag doesn't seem to work reliably. I'm not sure if it's a config issue at my end or not. In my config, I've marked `config`, `developer-tools`, and `hacs` as `bottom: true`, but only hacs seems to respect the flag and stick to the bottom.

Here's a screenshot:
![image](https://github.com/elchininet/custom-sidebar/assets/934532/b1dfcb3b-90b4-4274-9dbf-798410819251)

and here's my `sidebar-config.yaml` contents:
```
sidebar_editable: false
order:
  - item: overview
    order: 1
  - item: todo
    order: 2
  - item: energy
    order: 3
  - item: config
    order: 4
  - item: developer-tools
    order: 5
  - item: history
    hide: true
  - item: snapshots
    hide: true
  - item: backups
    hide: true
  - item: map
    hide: true
  - item: media
    hide: true
  - item: calendar
    hide: true
  - item: logbook
    hide: true
exceptions:
  - user:
      - Akshay
      - akshay
    order:
      - item: overview
        order: 1
      - item: todo
        order: 3
      - new_item: true
        item: Overseerr
        icon: mdi:play-network
        href: http://192.168.1.115:5055/
        order: 2
      - item: backups
        order: 4
      - new_item: true
        item: Integrations
        href: "/config/integrations"
        icon: mdi:puzzle
        order: 5
      - new_item: true
        item: Automations
        href: "/config/automations"
        icon: mdi:robot
        order: 6
      - item: df2164f9_ps5_mqtt
        hide: true
      - item: developer-tools
        order: 10
        # hide: true
        bottom: true
      - item: config
        order: 9
        bottom: true
      - item: hacs
        order: 7
        notification: '[[[ state_attr("sensor.hacs", "repositories").length || '' ]]]'
        bottom: true
      - item: energy
        order: 8
      - item: history
        hide: true
      - item: snapshots
        hide: true
      - item: map
        hide: true
      - item: media
        hide: true
      - item: calendar
        hide: true
      - item: logbook
        hide: true
```

**Comment by elchininet** [comment]
Hi @akshay7394,

In your screenshot I don't see any item named "developer-tools" but you are tyrying to match an item with that name using the name matcher (the default one). You should have a warning in your console warning you about that.

You should either change the `item` property to something that matches (like `developer`) or specify in the matcher property that you are trying to match by `data-panel`.

Regards

**Comment by akshay7394** [comment]
Ah, got it! My mistake. I've done that now, but my problem persists - though developer and settings moved a bit after I made the changes you mentioned. Now it looks like this:

![Screenshot_20240328-142943.png](https://github.com/elchininet/custom-sidebar/assets/934532/1b87d096-ebf8-4ca0-90b1-2ca0dd44d39f)

**Comment by elchininet** [comment]
Hi @akshay7394,
You didn't paste what was your final configuration to check what were your changes.
And also, did you check your console for warning/errors?
Regards

**Comment by akshay7394** [comment]
Sorry, my bad. Here's the config as it is now:

```
title: Windmills
sidebar_editable: false
order:
  - item: overview
    order: 1
  - item: todo
    order: 2
  - item: energy
    order: 3
  - item: settings
    order: 4
  - item: developer
    order: 5
    hide: true
  - item: history
    hide: true
  - item: snapshots
    hide: true
  - item: backups
    hide: true
  - item: map
    hide: true
  - item: media
    hide: true
  - item: calendar
    hide: true
  - item: logbook
    hide: true
exceptions:
  - user:
      - Akshay
      - akshay
    order:
      - item: overview
        order: 1
      - item: todo
        order: 3
      - new_item: true
        item: Overseerr
        icon: mdi:play-network
        href: http://192.168.1.115:5055/
        order: 2
      - item: backups
        order: 4
      - new_item: true
        item: Integrations
        href: "/config/integrations"
        icon: mdi:puzzle
        order: 5
      - new_item: true
        item: Automations
        href: "/config/automations"
        icon: mdi:robot
        order: 6
      - item: df2164f9_ps5_mqtt
        hide: true
      - item: developer
        order: 10
        # hide: true
        bottom: true
      - item: settings
        order: 9
        bottom: true
      - item: hacs
        order: 7
        notification: '[[[ state_attr("sensor.hacs", "repositories").length || '' ]]]'
        bottom: true
      - item: energy
        order: 8
      - item: history
        hide: true
      - item: snapshots
        hide: true
      - item: map
        hide: true
      - item: media
        hide: true
      - item: calendar
        hide: true
      - item: logbook
        hide: true
```


I'm not able to find it in the errors - but i could just be looking for it in the wrong place/with the wrong words. What should I look for? I searched for 'sidebar' 'develop' 'config' but none of them appeared in the logs.

**Comment by elchininet** [comment]
You should check in your browser console dev tools. If you are using Chrome right click on the screen and select `Inspect`, then go to `Console`. Let me know if there is any warning/error there.
Regards

**Comment by akshay7394** [comment]
Ah, got it! Totally my error, was looking in home assistant logs instead of in the browser console. I've removed/fixed the ones that were throwing warnings in the console. But now it still looks like this:
![image](https://github.com/elchininet/custom-sidebar/assets/934532/82a843ea-d5de-4584-a6e6-380c57ad25f5)


In the console, I see this info related to custom-sidebar (none of the yellow warnings that were there before i fixed `todo` etc):
```
GET http://homeassistant.local:8123/local/custom-sidebar-yaml.js?v1.0.0 net::ERR_ABORTED 404 (Not Found)
(anonymous) @ home:1
home:1 Uncaught (in promise) TypeError: Failed to fetch dynamically imported module: http://homeassistant.local:8123/local/custom-sidebar-yaml.js?v1.0.0
custom-sidebar-yaml.js?v1.0.0:1 ≡ CUSTOM-SIDEBAR (YAML)v4.5.1
VM881:3 Uncaught (in promise) SyntaxError: Invalid or unexpected token
    at new Function (<anonymous>)
    at e.renderTemplate (custom-sidebar-yaml.js?v1.0.0:1:22800)
    at o (custom-sidebar-yaml.js?v1.0.0:1:73861)
    at i._createJsTemplateSubscription (custom-sidebar-yaml.js?v1.0.0:1:74332)
    at i._subscribeTemplate (custom-sidebar-yaml.js?v1.0.0:1:73602)
    at i._subscribeNotification (custom-sidebar-yaml.js?v1.0.0:1:73329)
    at custom-sidebar-yaml.js?v1.0.0:1:80522
    at Array.forEach (<anonymous>)
    at custom-sidebar-yaml.js?v1.0.0:1:80140
```


And this is my current YAML after fixing the ones causing the yellow warning:
```

sidebar_editable: false
order:
  - item: overview
    order: 1
  - item: todo
    match: data-panel
    order: 2
  - item: energy
    order: 3
  - item: settings
    order: 4
  - item: developer
    order: 5
    hide: true
  - item: history
    hide: true
  - item: map
    hide: true
  - item: media
    hide: true
  - item: calendar
    hide: true
  - item: logbook
    hide: true
exceptions:
  - user:
      - Akshay
      - akshay
    order:
      - item: overview
        order: 1
      - item: todo
        match: data-panel
        order: 3
      - new_item: true
        item: Overseerr
        icon: mdi:play-network
        href: http://192.168.1.115:5055/
        order: 2
      - new_item: true
        item: Integrations
        href: "/config/integrations"
        icon: mdi:puzzle
        order: 5
      - new_item: true
        item: Automations
        href: "/config/automations"
        icon: mdi:robot
        order: 6
      - item: developer
        order: 10
        # hide: true
        bottom: true
      - item: settings
        order: 9
        bottom: true
      - item: hacs
        order: 7
        notification: '[[[ state_attr("sensor.hacs", "repositories").length || '' ]]]'
        bottom: true
      - item: energy
        order: 8
      - item: history
        hide: true
      - item: map
        hide: true
      - item: media
        hide: true
      - item: calendar
        hide: true
      - item: logbook
        hide: true
```
